// Rehearses the pending migrations. Builds the live-equivalent schema (everything the live database already has), then applies the pending
// migrations one at a time in the planned order, running the behaviour tests in scripts/sql-tests/rehearsal/ at the moment each one is due
// (some need the state just before or after a particular migration, e.g. "the old join path still works until 0238"). Prints, and writes to
// supabase/REHEARSAL.md, which migrations applied cleanly and which have behaviour proven in SQL.
//   node scripts/sql-tests/rehearsal.mjs
import { readdirSync, writeFileSync } from "node:fs";
import { createDb, applyLiveEquivalent, applyOne, makeHelpers, PLAN_ORDER, LIVE_EXTRA, migrationFile } from "./harness.mjs";

const testsDir = new URL("./rehearsal/", import.meta.url);
const modules = [];
for (const f of readdirSync(testsDir).filter((x) => x.endsWith(".test.mjs")).sort()) {
  modules.push((await import(new URL(f, testsDir).href)).default);
}

const db = await createDb();
const h = makeHelpers(db);
const liveNotes = await applyLiveEquivalent(db);
console.log("live-equivalent schema built" + (liveNotes.length ? `; files that did not apply from the repo (drift): ${liveNotes.join("; ")}` : ""));

// Per-test outcome: { name, migrations, passed, failed, crashed }
const outcomes = [];
async function runPhase(phase) {
  for (const m of modules) {
    const fn = m.phases?.[phase];
    if (!fn) continue;
    m.state ??= {};
    const before = h.results.length;
    let crashed = null;
    h.section(`${m.name} (${phase === "live" ? "on the live-equivalent schema" : "after " + phase})`);
    try {
      await fn({ db, h, state: m.state });
    } catch (e) {
      crashed = String(e.message).split("\n")[0];
      console.log(`CRASH ${m.name} @ ${phase}: ${crashed}`);
    }
    await h.asSuper();
    const mine = h.results.slice(before);
    outcomes.push({ name: m.name, migrations: m.migrations, phase, passed: mine.filter((r) => r.ok).length, failed: mine.filter((r) => !r.ok).length, crashed });
  }
}

await runPhase("live");
const applied = {};
for (const p of PLAN_ORDER) {
  const r = await applyOne(db, p);
  applied[p] = r;
  console.log(`\n>> applied ${migrationFile(p)}: ${r.ok ? "ok" : "FAILED " + r.error}`);
  if (r.ok) await runPhase(p);
}

// ---- summary ----------------------------------------------------------------------------------------------------------------------
const rows = [];
for (const p of [...LIVE_EXTRA.filter((x) => modules.some((m) => m.migrations.includes(x))), ...PLAN_ORDER]) {
  const live = LIVE_EXTRA.includes(p);
  const ap = live ? { ok: true } : applied[p];
  const mine = outcomes.filter((o) => o.migrations.includes(p));
  const passed = mine.reduce((s, o) => s + o.passed, 0);
  const failed = mine.reduce((s, o) => s + o.failed + (o.crashed ? 1 : 0), 0);
  const note = mine.map((o) => o.name).filter((v, i, a) => a.indexOf(v) === i).join("; ");
  rows.push({ p, live, applies: ap.ok, error: ap.error, passed, failed, note });
}

const line = (r) => {
  const rehearsed = r.applies && r.passed > 0 && r.failed === 0 ? "yes" : r.failed > 0 ? "FAILING" : r.applies ? "applies only" : "no";
  return `| ${r.p} | ${r.live ? "already live" : r.applies ? "yes" : "NO: " + r.error} | ${rehearsed} | ${r.passed}${r.failed ? ` (+${r.failed} failing)` : ""} | ${r.note || "-"} |`;
};
const md = [
  "# Migration rehearsal",
  "",
  "Generated by `node scripts/sql-tests/rehearsal.mjs`. The live-equivalent schema is every migration through 0235 plus " + LIVE_EXTRA.join(", ") +
    ", with the live definition of `complete_workout_session` (the repo text differs). The pending migrations are then applied one at a time in the planned order, and the behaviour tests run at the moment each is due.",
  "",
  "Not covered by this: the real database's data, real Supabase Auth, real storage, and the app calling these through PostgREST. It proves the SQL does what its comments say.",
  "",
  "| Migration | Applies in planned order | Rehearsed in SQL | Checks passing | What is tested |",
  "|---|---|---|---|---|",
  ...rows.map(line),
  "",
].join("\n");
writeFileSync(new URL("../../supabase/REHEARSAL.md", import.meta.url), md);
console.log("\n" + md);

const totalFailed = h.results.filter((r) => !r.ok).length + outcomes.filter((o) => o.crashed).length + Object.values(applied).filter((r) => !r.ok).length;
console.log(totalFailed === 0 ? `ALL PASSED (${h.results.length} checks)` : `${totalFailed} PROBLEMS`);
process.exit(totalFailed === 0 ? 0 : 1);
