// The bundled readings for Read during rest: the King James Version (public domain), verbatim, no verse numbers, each short enough to read in one rest.
// Generated once from vetted sources and then checked by lib/read-content/kjv-daily.test.ts; edit with care, and keep every reference unique.
import type { ReadItem } from "@/lib/read-content";

export const KJV_DAILY: ReadItem[] = [
  { ref: "Psalm 1:2-3", text: "But his delight is in the law of the LORD; and in his law doth he meditate day and night. And he shall be like a tree planted by the rivers of water, that bringeth forth his fruit in his season; his leaf also shall not wither; and whatsoever he doeth shall prosper." },
  { ref: "Psalm 3:3-5", text: "But thou, O LORD, art a shield for me; my glory, and the lifter up of mine head. I cried unto the LORD with my voice, and he heard me out of his holy hill. Selah. I laid me down and slept; I awaked; for the LORD sustained me." },
  { ref: "Psalm 4:7-8", text: "Thou hast put gladness in my heart, more than in the time that their corn and their wine increased. I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety." },
  { ref: "Psalm 5:11-12", text: "But let all those that put their trust in thee rejoice: let them ever shout for joy, because thou defendest them: let them also that love thy name be joyful in thee. For thou, LORD, wilt bless the righteous; with favour wilt thou compass him as with a shield." },
  { ref: "Psalm 6:9", text: "The LORD hath heard my supplication; the LORD will receive my prayer." },
  { ref: "Psalm 7:17", text: "I will praise the LORD according to his righteousness: and will sing praise to the name of the LORD most high." },
  { ref: "Psalm 8:3-4", text: "When I consider thy heavens, the work of thy fingers, the moon and the stars, which thou hast ordained; What is man, that thou art mindful of him? and the son of man, that thou visitest him?" },
  { ref: "Psalm 9:9-10", text: "The LORD also will be a refuge for the oppressed, a refuge in times of trouble. And they that know thy name will put their trust in thee: for thou, LORD, hast not forsaken them that seek thee." },
  { ref: "Psalm 10:17-18", text: "LORD, thou hast heard the desire of the humble: thou wilt prepare their heart, thou wilt cause thine ear to hear: To judge the fatherless and the oppressed, that the man of the earth may no more oppress." },
  { ref: "Psalm 11:7", text: "For the righteous LORD loveth righteousness; his countenance doth behold the upright." },
  { ref: "Psalm 12:6", text: "The words of the LORD are pure words: as silver tried in a furnace of earth, purified seven times." },
  { ref: "Psalm 13:5-6", text: "But I have trusted in thy mercy; my heart shall rejoice in thy salvation. I will sing unto the LORD, because he hath dealt bountifully with me." },
  { ref: "Psalm 16:8-9", text: "I have set the LORD always before me: because he is at my right hand, I shall not be moved. Therefore my heart is glad, and my glory rejoiceth: my flesh also shall rest in hope." },
  { ref: "Psalm 17:15", text: "As for me, I will behold thy face in righteousness: I shall be satisfied, when I awake, with thy likeness." },
  { ref: "Psalm 18:32-33", text: "It is God that girdeth me with strength, and maketh my way perfect. He maketh my feet like hinds' feet, and setteth me upon my high places." },
  { ref: "Psalm 19:14", text: "Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O LORD, my strength, and my redeemer." },
  { ref: "Psalm 20:4-5", text: "Grant thee according to thine own heart, and fulfil all thy counsel. We will rejoice in thy salvation, and in the name of our God we will set up our banners: the LORD fulfil all thy petitions." },
  { ref: "Psalm 21:1-2", text: "The king shall joy in thy strength, O LORD; and in thy salvation how greatly shall he rejoice! Thou hast given him his heart's desire, and hast not withholden the request of his lips. Selah." },
  { ref: "Psalm 22:3-4", text: "But thou art holy, O thou that inhabitest the praises of Israel. Our fathers trusted in thee: they trusted, and thou didst deliver them." },
  { ref: "Psalm 23:1-3", text: "The LORD is my shepherd; I shall not want. He maketh me to lie down in green pastures: he leadeth me beside the still waters. He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake." },
  { ref: "Psalm 24:1-2", text: "The earth is the LORD's, and the fulness thereof; the world, and they that dwell therein. For he hath founded it upon the seas, and established it upon the floods." },
  { ref: "Psalm 25:4-5", text: "Shew me thy ways, O LORD; teach me thy paths. Lead me in thy truth, and teach me: for thou art the God of my salvation; on thee do I wait all the day." },
  { ref: "Psalm 26:12", text: "My foot standeth in an even place: in the congregations will I bless the LORD." },
  { ref: "Psalm 27:13-14", text: "I had fainted, unless I had believed to see the goodness of the LORD in the land of the living. Wait on the LORD: be of good courage, and he shall strengthen thine heart: wait, I say, on the LORD." },
  { ref: "Psalm 28:7", text: "The LORD is my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him." },
  { ref: "Psalm 29:11", text: "The LORD will give strength unto his people; the LORD will bless his people with peace." },
  { ref: "Psalm 30:11-12", text: "Thou hast turned for me my mourning into dancing: thou hast put off my sackcloth, and girded me with gladness; To the end that my glory may sing praise to thee, and not be silent. O LORD my God, I will give thanks unto thee for ever." },
  { ref: "Psalm 31:24", text: "Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD." },
  { ref: "Psalm 32:7-8", text: "Thou art my hiding place; thou shalt preserve me from trouble; thou shalt compass me about with songs of deliverance. Selah. I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye." },
  { ref: "Psalm 33:20-22", text: "Our soul waiteth for the LORD: he is our help and our shield. For our heart shall rejoice in him, because we have trusted in his holy name. Let thy mercy, O LORD, be upon us, according as we hope in thee." },
  { ref: "Psalm 34:1-3", text: "I will bless the LORD at all times: his praise shall continually be in my mouth. My soul shall make her boast in the LORD: the humble shall hear thereof, and be glad. O magnify the LORD with me, and let us exalt his name together." },
  { ref: "Psalm 36:7", text: "How excellent is thy lovingkindness, O God! therefore the children of men put their trust under the shadow of thy wings." },
  { ref: "Psalm 37:3-5", text: "Trust in the LORD, and do good; so shalt thou dwell in the land, and verily thou shalt be fed. Delight thyself also in the LORD; and he shall give thee the desires of thine heart. Commit thy way unto the LORD; trust also in him; and he shall bring it to pass." },
  { ref: "Psalm 37:23-24", text: "The steps of a good man are ordered by the LORD: and he delighteth in his way. Though he fall, he shall not be utterly cast down: for the LORD upholdeth him with his hand." },
  { ref: "Psalm 38:15", text: "For in thee, O LORD, do I hope: thou wilt hear, O Lord my God." },
  { ref: "Psalm 39:7", text: "And now, Lord, what wait I for? my hope is in thee." },
  { ref: "Psalm 40:1-2", text: "I waited patiently for the LORD; and he inclined unto me, and heard my cry. He brought me up also out of an horrible pit, out of the miry clay, and set my feet upon a rock, and established my goings." },
  { ref: "Psalm 41:1", text: "Blessed is he that considereth the poor: the LORD will deliver him in time of trouble." },
  { ref: "Psalm 42:5", text: "Why art thou cast down, O my soul? and why art thou disquieted in me? hope thou in God: for I shall yet praise him for the help of his countenance." },
  { ref: "Psalm 43:3-4", text: "O send out thy light and thy truth: let them lead me; let them bring me unto thy holy hill, and to thy tabernacles. Then will I go unto the altar of God, unto God my exceeding joy: yea, upon the harp will I praise thee, O God my God." },
  { ref: "Psalm 46:10-11", text: "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth. The LORD of hosts is with us; the God of Jacob is our refuge. Selah." },
  { ref: "Psalm 47:1", text: "O clap your hands, all ye people; shout unto God with the voice of triumph." },
  { ref: "Psalm 48:9-10", text: "We have thought of thy lovingkindness, O God, in the midst of thy temple. According to thy name, O God, so is thy praise unto the ends of the earth: thy right hand is full of righteousness." },
  { ref: "Psalm 50:14-15", text: "Offer unto God thanksgiving; and pay thy vows unto the most High: And call upon me in the day of trouble: I will deliver thee, and thou shalt glorify me." },
  { ref: "Psalm 51:10-12", text: "Create in me a clean heart, O God; and renew a right spirit within me. Cast me not away from thy presence; and take not thy holy spirit from me. Restore unto me the joy of thy salvation; and uphold me with thy free spirit." },
  { ref: "Psalm 52:8", text: "But I am like a green olive tree in the house of God: I trust in the mercy of God for ever and ever." },
  { ref: "Psalm 54:4", text: "Behold, God is mine helper: the Lord is with them that uphold my soul." },
  { ref: "Psalm 55:22", text: "Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved." },
  { ref: "Psalm 56:3-4", text: "What time I am afraid, I will trust in thee. In God I will praise his word, in God I have put my trust; I will not fear what flesh can do unto me." },
  { ref: "Psalm 57:7", text: "My heart is fixed, O God, my heart is fixed: I will sing and give praise." },
  { ref: "Psalm 59:16", text: "But I will sing of thy power; yea, I will sing aloud of thy mercy in the morning: for thou hast been my defence and refuge in the day of my trouble." },
  { ref: "Psalm 61:1-2", text: "Hear my cry, O God; attend unto my prayer. From the end of the earth will I cry unto thee, when my heart is overwhelmed: lead me to the rock that is higher than I." },
  { ref: "Psalm 62:1-2", text: "Truly my soul waiteth upon God: from him cometh my salvation. He only is my rock and my salvation; he is my defence; I shall not be greatly moved." },
  { ref: "Psalm 63:6-8", text: "When I remember thee upon my bed, and meditate on thee in the night watches. Because thou hast been my help, therefore in the shadow of thy wings will I rejoice. My soul followeth hard after thee: thy right hand upholdeth me." },
  { ref: "Psalm 64:10", text: "The righteous shall be glad in the LORD, and shall trust in him; and all the upright in heart shall glory." },
  { ref: "Psalm 65:13", text: "The pastures are clothed with flocks; the valleys also are covered over with corn; they shout for joy, they also sing." },
  { ref: "Psalm 66:8-9", text: "O bless our God, ye people, and make the voice of his praise to be heard: Which holdeth our soul in life, and suffereth not our feet to be moved." },
  { ref: "Psalm 67:1-2", text: "God be merciful unto us, and bless us; and cause his face to shine upon us; Selah. That thy way may be known upon earth, thy saving health among all nations." },
  { ref: "Psalm 68:19", text: "Blessed be the Lord, who daily loadeth us with benefits, even the God of our salvation. Selah." },
  { ref: "Psalm 69:30", text: "I will praise the name of God with a song, and will magnify him with thanksgiving." },
  { ref: "Psalm 70:4", text: "Let all those that seek thee rejoice and be glad in thee: and let such as love thy salvation say continually, Let God be magnified." },
  { ref: "Psalm 71:14", text: "But I will hope continually, and will yet praise thee more and more." },
  { ref: "Psalm 72:18-19", text: "Blessed be the LORD God, the God of Israel, who only doeth wondrous things. And blessed be his glorious name for ever: and let the whole earth be filled with his glory; Amen, and Amen." },
  { ref: "Psalm 73:23-24", text: "Nevertheless I am continually with thee: thou hast holden me by my right hand. Thou shalt guide me with thy counsel, and afterward receive me to glory." },
  { ref: "Psalm 75:1", text: "Unto thee, O God, do we give thanks, unto thee do we give thanks: for that thy name is near thy wondrous works declare." },
  { ref: "Psalm 77:11-12", text: "I will remember the works of the LORD: surely I will remember thy wonders of old. I will meditate also of all thy work, and talk of thy doings." },
  { ref: "Psalm 80:3", text: "Turn us again, O God, and cause thy face to shine; and we shall be saved." },
  { ref: "Psalm 81:1", text: "Sing aloud unto God our strength: make a joyful noise unto the God of Jacob." },
  { ref: "Psalm 84:5-7", text: "Blessed is the man whose strength is in thee; in whose heart are the ways of them. Who passing through the valley of Baca make it a well; the rain also filleth the pools. They go from strength to strength, every one of them in Zion appeareth before God." },
  { ref: "Psalm 85:10-11", text: "Mercy and truth are met together; righteousness and peace have kissed each other. Truth shall spring out of the earth; and righteousness shall look down from heaven." },
  { ref: "Psalm 86:11-12", text: "Teach me thy way, O LORD; I will walk in thy truth: unite my heart to fear thy name. I will praise thee, O Lord my God, with all my heart: and I will glorify thy name for evermore." },
  { ref: "Psalm 89:1-2", text: "I will sing of the mercies of the LORD for ever: with my mouth will I make known thy faithfulness to all generations. For I have said, Mercy shall be built up for ever: thy faithfulness shalt thou establish in the very heavens." },
  { ref: "Psalm 89:15-16", text: "Blessed is the people that know the joyful sound: they shall walk, O LORD, in the light of thy countenance. In thy name shall they rejoice all the day: and in thy righteousness shall they be exalted." },
  { ref: "Psalm 90:17", text: "And let the beauty of the LORD our God be upon us: and establish thou the work of our hands upon us; yea, the work of our hands establish thou it." },
  { ref: "Psalm 91:1-2", text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty. I will say of the LORD, He is my refuge and my fortress: my God; in him will I trust." },
  { ref: "Psalm 92:1-3", text: "It is a good thing to give thanks unto the LORD, and to sing praises unto thy name, O most High: To shew forth thy lovingkindness in the morning, and thy faithfulness every night, Upon an instrument of ten strings, and upon the psaltery; upon the harp with a solemn sound." },
  { ref: "Psalm 93:4", text: "The LORD on high is mightier than the noise of many waters, yea, than the mighty waves of the sea." },
  { ref: "Psalm 94:18-19", text: "When I said, My foot slippeth; thy mercy, O LORD, held me up. In the multitude of my thoughts within me thy comforts delight my soul." },
  { ref: "Psalm 95:1-2", text: "O come, let us sing unto the LORD: let us make a joyful noise to the rock of our salvation. Let us come before his presence with thanksgiving, and make a joyful noise unto him with psalms." },
  { ref: "Psalm 96:1-2", text: "O sing unto the LORD a new song: sing unto the LORD, all the earth. Sing unto the LORD, bless his name; shew forth his salvation from day to day." },
  { ref: "Psalm 97:11-12", text: "Light is sown for the righteous, and gladness for the upright in heart. Rejoice in the LORD, ye righteous; and give thanks at the remembrance of his holiness." },
  { ref: "Psalm 98:4-5", text: "Make a joyful noise unto the LORD, all the earth: make a loud noise, and rejoice, and sing praise. Sing unto the LORD with the harp; with the harp, and the voice of a psalm." },
  { ref: "Psalm 100:4-5", text: "Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name. For the LORD is good; his mercy is everlasting; and his truth endureth to all generations." },
  { ref: "Psalm 103:13", text: "Like as a father pitieth his children, so the LORD pitieth them that fear him." },
  { ref: "Psalm 104:33-34", text: "I will sing unto the LORD as long as I live: I will sing praise to my God while I have my being. My meditation of him shall be sweet: I will be glad in the LORD." },
  { ref: "Psalm 105:3-4", text: "Glory ye in his holy name: let the heart of them rejoice that seek the LORD. Seek the LORD, and his strength: seek his face evermore." },
  { ref: "Psalm 106:1", text: "Praise ye the LORD. O give thanks unto the LORD; for he is good: for his mercy endureth for ever." },
  { ref: "Psalm 107:8-9", text: "Oh that men would praise the LORD for his goodness, and for his wonderful works to the children of men! For he satisfieth the longing soul, and filleth the hungry soul with goodness." },
  { ref: "Psalm 107:28-30", text: "Then they cry unto the LORD in their trouble, and he bringeth them out of their distresses. He maketh the storm a calm, so that the waves thereof are still. Then are they glad because they be quiet; so he bringeth them unto their desired haven." },
  { ref: "Psalm 111:1-2", text: "Praise ye the LORD. I will praise the LORD with my whole heart, in the assembly of the upright, and in the congregation. The works of the LORD are great, sought out of all them that have pleasure therein." },
  { ref: "Psalm 112:6-7", text: "Surely he shall not be moved for ever: the righteous shall be in everlasting remembrance. He shall not be afraid of evil tidings: his heart is fixed, trusting in the LORD." },
  { ref: "Psalm 113:2-3", text: "Blessed be the name of the LORD from this time forth and for evermore. From the rising of the sun unto the going down of the same the LORD's name is to be praised." },
  { ref: "Psalm 115:1", text: "Not unto us, O LORD, not unto us, but unto thy name give glory, for thy mercy, and for thy truth's sake." },
  { ref: "Psalm 116:7", text: "Return unto thy rest, O my soul; for the LORD hath dealt bountifully with thee." },
  { ref: "Psalm 117:1-2", text: "O praise the LORD, all ye nations: praise him, all ye people. For his merciful kindness is great toward us: and the truth of the LORD endureth for ever. Praise ye the LORD." },
  { ref: "Psalm 118:24", text: "This is the day which the LORD hath made; we will rejoice and be glad in it." },
  { ref: "Psalm 119:28", text: "My soul melteth for heaviness: strengthen thou me according unto thy word." },
  { ref: "Psalm 119:32", text: "I will run the way of thy commandments, when thou shalt enlarge my heart." },
  { ref: "Psalm 119:45", text: "And I will walk at liberty: for I seek thy precepts." },
  { ref: "Psalm 119:105", text: "Thy word is a lamp unto my feet, and a light unto my path." },
  { ref: "Psalm 119:114", text: "Thou art my hiding place and my shield: I hope in thy word." },
  { ref: "Psalm 119:165", text: "Great peace have they which love thy law: and nothing shall offend them." },
  { ref: "Psalm 121:1-3", text: "I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD, which made heaven and earth. He will not suffer thy foot to be moved: he that keepeth thee will not slumber." },
  { ref: "Psalm 122:1", text: "I was glad when they said unto me, Let us go into the house of the LORD." },
  { ref: "Psalm 124:8", text: "Our help is in the name of the LORD, who made heaven and earth." },
  { ref: "Psalm 125:1-2", text: "They that trust in the LORD shall be as mount Zion, which cannot be removed, but abideth for ever. As the mountains are round about Jerusalem, so the LORD is round about his people from henceforth even for ever." },
  { ref: "Psalm 126:5-6", text: "They that sow in tears shall reap in joy. He that goeth forth and weepeth, bearing precious seed, shall doubtless come again with rejoicing, bringing his sheaves with him." },
  { ref: "Psalm 127:1-2", text: "Except the LORD build the house, they labour in vain that build it: except the LORD keep the city, the watchman waketh but in vain. It is vain for you to rise up early, to sit up late, to eat the bread of sorrows: for so he giveth his beloved sleep." },
  { ref: "Psalm 128:1-2", text: "Blessed is every one that feareth the LORD; that walketh in his ways. For thou shalt eat the labour of thine hands: happy shalt thou be, and it shall be well with thee." },
  { ref: "Psalm 130:5-6", text: "I wait for the LORD, my soul doth wait, and in his word do I hope. My soul waiteth for the Lord more than they that watch for the morning: I say, more than they that watch for the morning." },
  { ref: "Psalm 131:1-2", text: "LORD, my heart is not haughty, nor mine eyes lofty: neither do I exercise myself in great matters, or in things too high for me. Surely I have behaved and quieted myself, as a child that is weaned of his mother: my soul is even as a weaned child." },
  { ref: "Psalm 133:1", text: "Behold, how good and how pleasant it is for brethren to dwell together in unity!" },
  { ref: "Psalm 134:1-2", text: "Behold, bless ye the LORD, all ye servants of the LORD, which by night stand in the house of the LORD. Lift up your hands in the sanctuary, and bless the LORD." },
  { ref: "Psalm 135:3", text: "Praise the LORD; for the LORD is good: sing praises unto his name; for it is pleasant." },
  { ref: "Psalm 136:1-3", text: "O give thanks unto the LORD; for he is good: for his mercy endureth for ever. O give thanks unto the God of gods: for his mercy endureth for ever. O give thanks to the Lord of lords: for his mercy endureth for ever." },
  { ref: "Psalm 138:3", text: "In the day when I cried thou answeredst me, and strengthenedst me with strength in my soul." },
  { ref: "Psalm 139:14", text: "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well." },
  { ref: "Psalm 142:5", text: "I cried unto thee, O LORD: I said, Thou art my refuge and my portion in the land of the living." },
  { ref: "Psalm 143:8", text: "Cause me to hear thy lovingkindness in the morning; for in thee do I trust: cause me to know the way wherein I should walk; for I lift up my soul unto thee." },
  { ref: "Psalm 145:8-9", text: "The LORD is gracious, and full of compassion; slow to anger, and of great mercy. The LORD is good to all: and his tender mercies are over all his works." },
  { ref: "Psalm 146:1-2", text: "Praise ye the LORD. Praise the LORD, O my soul. While I live will I praise the LORD: I will sing praises unto my God while I have any being." },
  { ref: "Psalm 147:3-4", text: "He healeth the broken in heart, and bindeth up their wounds. He telleth the number of the stars; he calleth them all by their names." },
  { ref: "Psalm 148:3-4", text: "Praise ye him, sun and moon: praise him, all ye stars of light. Praise him, ye heavens of heavens, and ye waters that be above the heavens." },
  { ref: "Psalm 149:4", text: "For the LORD taketh pleasure in his people: he will beautify the meek with salvation." },
  { ref: "Psalm 150:6", text: "Let every thing that hath breath praise the LORD. Praise ye the LORD." },
  { ref: "Proverbs 3:5-6", text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths." },
  { ref: "Proverbs 3:13-14", text: "Happy is the man that findeth wisdom, and the man that getteth understanding. For the merchandise of it is better than the merchandise of silver, and the gain thereof than fine gold." },
  { ref: "Proverbs 3:24", text: "When thou liest down, thou shalt not be afraid: yea, thou shalt lie down, and thy sleep shall be sweet." },
  { ref: "Proverbs 4:7", text: "Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding." },
  { ref: "Proverbs 4:18", text: "But the path of the just is as the shining light, that shineth more and more unto the perfect day." },
  { ref: "Proverbs 4:23", text: "Keep thy heart with all diligence; for out of it are the issues of life." },
  { ref: "Proverbs 2:6-7", text: "For the LORD giveth wisdom: out of his mouth cometh knowledge and understanding. He layeth up sound wisdom for the righteous: he is a buckler to them that walk uprightly." },
  { ref: "Proverbs 10:4", text: "He becometh poor that dealeth with a slack hand: but the hand of the diligent maketh rich." },
  { ref: "Proverbs 11:14", text: "Where no counsel is, the people fall: but in the multitude of counsellors there is safety." },
  { ref: "Proverbs 12:25", text: "Heaviness in the heart of man maketh it stoop: but a good word maketh it glad." },
  { ref: "Proverbs 13:11", text: "Wealth gotten by vanity shall be diminished: but he that gathereth by labour shall increase." },
  { ref: "Proverbs 13:12", text: "Hope deferred maketh the heart sick: but when the desire cometh, it is a tree of life." },
  { ref: "Proverbs 14:23", text: "In all labour there is profit: but the talk of the lips tendeth only to penury." },
  { ref: "Proverbs 14:26", text: "In the fear of the LORD is strong confidence: and his children shall have a place of refuge." },
  { ref: "Proverbs 14:29", text: "He that is slow to wrath is of great understanding: but he that is hasty of spirit exalteth folly." },
  { ref: "Proverbs 15:1", text: "A soft answer turneth away wrath: but grievous words stir up anger." },
  { ref: "Proverbs 15:13", text: "A merry heart maketh a cheerful countenance: but by sorrow of the heart the spirit is broken." },
  { ref: "Proverbs 15:22", text: "Without counsel purposes are disappointed: but in the multitude of counsellors they are established." },
  { ref: "Proverbs 16:3", text: "Commit thy works unto the LORD, and thy thoughts shall be established." },
  { ref: "Proverbs 16:9", text: "A man's heart deviseth his way: but the LORD directeth his steps." },
  { ref: "Proverbs 16:20", text: "He that handleth a matter wisely shall find good: and whoso trusteth in the LORD, happy is he." },
  { ref: "Proverbs 16:24", text: "Pleasant words are as an honeycomb, sweet to the soul, and health to the bones." },
  { ref: "Proverbs 16:32", text: "He that is slow to anger is better than the mighty; and he that ruleth his spirit than he that taketh a city." },
  { ref: "Proverbs 17:17", text: "A friend loveth at all times, and a brother is born for adversity." },
  { ref: "Proverbs 17:22", text: "A merry heart doeth good like a medicine: but a broken spirit drieth the bones." },
  { ref: "Proverbs 17:27", text: "He that hath knowledge spareth his words: and a man of understanding is of an excellent spirit." },
  { ref: "Proverbs 18:10", text: "The name of the LORD is a strong tower: the righteous runneth into it, and is safe." },
  { ref: "Proverbs 19:11", text: "The discretion of a man deferreth his anger; and it is his glory to pass over a transgression." },
  { ref: "Proverbs 19:21", text: "There are many devices in a man's heart; nevertheless the counsel of the LORD, that shall stand." },
  { ref: "Proverbs 21:5", text: "The thoughts of the diligent tend only to plenteousness; but of every one that is hasty only to want." },
  { ref: "Proverbs 21:21", text: "He that followeth after righteousness and mercy findeth life, righteousness, and honour." },
  { ref: "Proverbs 22:1", text: "A good name is rather to be chosen than great riches, and loving favour rather than silver and gold." },
  { ref: "Proverbs 22:4", text: "By humility and the fear of the LORD are riches, and honour, and life." },
  { ref: "Proverbs 22:29", text: "Seest thou a man diligent in his business? he shall stand before kings; he shall not stand before mean men." },
  { ref: "Proverbs 24:3-4", text: "Through wisdom is an house builded; and by understanding it is established: And by knowledge shall the chambers be filled with all precious and pleasant riches." },
  { ref: "Proverbs 25:15", text: "By long forbearing is a prince persuaded, and a soft tongue breaketh the bone." },
  { ref: "Proverbs 25:28", text: "He that hath no rule over his own spirit is like a city that is broken down, and without walls." },
  { ref: "Proverbs 27:9", text: "Ointment and perfume rejoice the heart: so doth the sweetness of a man's friend by hearty counsel." },
  { ref: "Proverbs 27:17", text: "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend." },
  { ref: "Proverbs 29:25", text: "The fear of man bringeth a snare: but whoso putteth his trust in the LORD shall be safe." },
  { ref: "Proverbs 31:25", text: "Strength and honour are her clothing; and she shall rejoice in time to come." },
  { ref: "Proverbs 15:23", text: "A man hath joy by the answer of his mouth: and a word spoken in due season, how good is it!" },
  { ref: "Proverbs 17:1", text: "Better is a dry morsel, and quietness therewith, than an house full of sacrifices with strife." },
  { ref: "Proverbs 23:18", text: "For surely there is an end; and thine expectation shall not be cut off." },
  { ref: "Proverbs 24:5", text: "A wise man is strong; yea, a man of knowledge increaseth strength." },
  { ref: "Ecclesiastes 3:11", text: "He hath made every thing beautiful in his time: also he hath set the world in their heart, so that no man can find out the work that God maketh from the beginning to the end." },
  { ref: "Ecclesiastes 3:12-13", text: "I know that there is no good in them, but for a man to rejoice, and to do good in his life. And also that every man should eat and drink, and enjoy the good of all his labour, it is the gift of God." },
  { ref: "Ecclesiastes 4:9-10", text: "Two are better than one; because they have a good reward for their labour. For if they fall, the one will lift up his fellow: but woe to him that is alone when he falleth; for he hath not another to help him up." },
  { ref: "Ecclesiastes 4:12", text: "And if one prevail against him, two shall withstand him; and a threefold cord is not quickly broken." },
  { ref: "Ecclesiastes 5:12", text: "The sleep of a labouring man is sweet, whether he eat little or much: but the abundance of the rich will not suffer him to sleep." },
  { ref: "Ecclesiastes 7:8", text: "Better is the end of a thing than the beginning thereof: and the patient in spirit is better than the proud in spirit." },
  { ref: "Ecclesiastes 9:10", text: "Whatsoever thy hand findeth to do, do it with thy might; for there is no work, nor device, nor knowledge, nor wisdom, in the grave, whither thou goest." },
  { ref: "Ecclesiastes 11:6", text: "In the morning sow thy seed, and in the evening withhold not thine hand: for thou knowest not whether shall prosper, either this or that, or whether they both shall be alike good." },
  { ref: "Ecclesiastes 5:19", text: "Every man also to whom God hath given riches and wealth, and hath given him power to eat thereof, and to take his portion, and to rejoice in his labour; this is the gift of God." },
  { ref: "Ecclesiastes 11:1", text: "Cast thy bread upon the waters: for thou shalt find it after many days." },
  { ref: "Isaiah 12:2", text: "Behold, God is my salvation; I will trust, and not be afraid: for the LORD JEHOVAH is my strength and my song; he also is become my salvation." },
  { ref: "Isaiah 12:3", text: "Therefore with joy shall ye draw water out of the wells of salvation." },
  { ref: "Isaiah 26:3", text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee." },
  { ref: "Isaiah 30:21", text: "And thine ears shall hear a word behind thee, saying, This is the way, walk ye in it, when ye turn to the right hand, and when ye turn to the left." },
  { ref: "Isaiah 33:2", text: "O LORD, be gracious unto us; we have waited for thee: be thou their arm every morning, our salvation also in the time of trouble." },
  { ref: "Isaiah 40:11", text: "He shall feed his flock like a shepherd: he shall gather the lambs with his arm, and carry them in his bosom, and shall gently lead those that are with young." },
  { ref: "Isaiah 40:28-29", text: "Hast thou not known? hast thou not heard, that the everlasting God, the LORD, the Creator of the ends of the earth, fainteth not, neither is weary? there is no searching of his understanding. He giveth power to the faint; and to them that have no might he increaseth strength." },
  { ref: "Isaiah 40:31", text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint." },
  { ref: "Isaiah 41:10", text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness." },
  { ref: "Isaiah 41:13", text: "For I the LORD thy God will hold thy right hand, saying unto thee, Fear not; I will help thee." },
  { ref: "Isaiah 43:19", text: "Behold, I will do a new thing; now it shall spring forth; shall ye not know it? I will even make a way in the wilderness, and rivers in the desert." },
  { ref: "Isaiah 46:4", text: "And even to your old age I am he; and even to hoar hairs will I carry you: I have made, and I will bear; even I will carry, and will deliver you." },
  { ref: "Isaiah 48:17", text: "Thus saith the LORD, thy Redeemer, the Holy One of Israel; I am the LORD thy God which teacheth thee to profit, which leadeth thee by the way that thou shouldest go." },
  { ref: "Isaiah 50:4", text: "The Lord GOD hath given me the tongue of the learned, that I should know how to speak a word in season to him that is weary: he wakeneth morning by morning, he wakeneth mine ear to hear as the learned." },
  { ref: "Isaiah 50:7", text: "For the Lord GOD will help me; therefore shall I not be confounded: therefore have I set my face like a flint, and I know that I shall not be ashamed." },
  { ref: "Isaiah 51:11", text: "Therefore the redeemed of the LORD shall return, and come with singing unto Zion; and everlasting joy shall be upon their head: they shall obtain gladness and joy; and sorrow and mourning shall flee away." },
  { ref: "Isaiah 54:10", text: "For the mountains shall depart, and the hills be removed; but my kindness shall not depart from thee, neither shall the covenant of my peace be removed, saith the LORD that hath mercy on thee." },
  { ref: "Isaiah 54:13", text: "And all thy children shall be taught of the LORD; and great shall be the peace of thy children." },
  { ref: "Isaiah 55:8-9", text: "For my thoughts are not your thoughts, neither are your ways my ways, saith the LORD. For as the heavens are higher than the earth, so are my ways higher than your ways, and my thoughts than your thoughts." },
  { ref: "Isaiah 55:12", text: "For ye shall go out with joy, and be led forth with peace: the mountains and the hills shall break forth before you into singing, and all the trees of the field shall clap their hands." },
  { ref: "Isaiah 57:15", text: "For thus saith the high and lofty One that inhabiteth eternity, whose name is Holy; I dwell in the high and holy place, with him also that is of a contrite and humble spirit, to revive the spirit of the humble, and to revive the heart of the contrite ones." },
  { ref: "Isaiah 58:11", text: "And the LORD shall guide thee continually, and satisfy thy soul in drought, and make fat thy bones: and thou shalt be like a watered garden, and like a spring of water, whose waters fail not." },
  { ref: "Isaiah 66:13", text: "As one whom his mother comforteth, so will I comfort you; and ye shall be comforted in Jerusalem." },
  { ref: "Isaiah 49:13", text: "Sing, O heavens; and be joyful, O earth; and break forth into singing, O mountains: for the LORD hath comforted his people, and will have mercy upon his afflicted." },
  { ref: "Isaiah 43:2", text: "When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee: when thou walkest through the fire, thou shalt not be burned; neither shall the flame kindle upon thee." },
  { ref: "Job 8:7", text: "Though thy beginning was small, yet thy latter end should greatly increase." },
  { ref: "Job 11:18", text: "And thou shalt be secure, because there is hope; yea, thou shalt dig about thee, and thou shalt take thy rest in safety." },
  { ref: "Job 17:9", text: "The righteous also shall hold on his way, and he that hath clean hands shall be stronger and stronger." },
  { ref: "Job 22:21", text: "Acquaint now thyself with him, and be at peace: thereby good shall come unto thee." },
  { ref: "Job 23:10", text: "But he knoweth the way that I take: when he hath tried me, I shall come forth as gold." },
  { ref: "Lamentations 3:22-23", text: "It is of the LORD'S mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness." },
  { ref: "Lamentations 3:24", text: "The LORD is my portion, saith my soul; therefore will I hope in him." },
  { ref: "Lamentations 3:25-26", text: "The LORD is good unto them that wait for him, to the soul that seeketh him. It is good that a man should both hope and quietly wait for the salvation of the LORD." },
  { ref: "Jeremiah 17:7", text: "Blessed is the man that trusteth in the LORD, and whose hope the LORD is." },
  { ref: "Jeremiah 29:11", text: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end." },
  { ref: "Jeremiah 29:13", text: "And ye shall seek me, and find me, when ye shall search for me with all your heart." },
  { ref: "Jeremiah 31:3", text: "The LORD hath appeared of old unto me, saying, Yea, I have loved thee with an everlasting love: therefore with lovingkindness have I drawn thee." },
  { ref: "Jeremiah 31:25", text: "For I have satiated the weary soul, and I have replenished every sorrowful soul." },
  { ref: "Jeremiah 33:3", text: "Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not." },
  { ref: "Jeremiah 1:8", text: "Be not afraid of their faces: for I am with thee to deliver thee, saith the LORD." },
  { ref: "Jeremiah 31:16", text: "Thus saith the LORD; Refrain thy voice from weeping, and thine eyes from tears: for thy work shall be rewarded, saith the LORD; and they shall come again from the land of the enemy." },
  { ref: "Micah 6:8", text: "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?" },
  { ref: "Micah 7:7", text: "Therefore I will look unto the LORD; I will wait for the God of my salvation: my God will hear me." },
  { ref: "Habakkuk 3:19", text: "The LORD God is my strength, and he will make my feet like hinds' feet, and he will make me to walk upon mine high places." },
  { ref: "Habakkuk 2:3", text: "For the vision is yet for an appointed time, but at the end it shall speak, and not lie: though it tarry, wait for it; because it will surely come, it will not tarry." },
  { ref: "Zephaniah 3:17", text: "The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing." },
  { ref: "Joshua 1:9", text: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest." },
  { ref: "Joshua 1:7", text: "Only be thou strong and very courageous, that thou mayest observe to do according to all the law, which Moses my servant commanded thee: turn not from it to the right hand or to the left, that thou mayest prosper whithersoever thou goest." },
  { ref: "Joshua 1:8", text: "This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night, that thou mayest observe to do according to all that is written therein: for then thou shalt make thy way prosperous, and then thou shalt have good success." },
  { ref: "Deuteronomy 31:6", text: "Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee." },
  { ref: "Deuteronomy 31:8", text: "And the LORD, he it is that doth go before thee; he will be with thee, he will not fail thee, neither forsake thee: fear not, neither be dismayed." },
  { ref: "Deuteronomy 31:7", text: "And Moses called unto Joshua, and said unto him in the sight of all Israel, Be strong and of a good courage: for thou must go with this people unto the land which the LORD hath sworn unto their fathers to give them; and thou shalt cause them to inherit it." },
  { ref: "Deuteronomy 33:25", text: "Thy shoes shall be iron and brass; and as thy days, so shall thy strength be." },
  { ref: "Deuteronomy 1:21", text: "Behold, the LORD thy God hath set the land before thee: go up and possess it, as the LORD God of thy fathers hath said unto thee; fear not, neither be discouraged." },
  { ref: "1 Samuel 12:24", text: "Only fear the LORD, and serve him in truth with all your heart: for consider how great things he hath done for you." },
  { ref: "1 Samuel 12:22", text: "For the LORD will not forsake his people for his great name's sake: because it hath pleased the LORD to make you his people." },
  { ref: "1 Kings 3:9", text: "Give therefore thy servant an understanding heart to judge thy people, that I may discern between good and bad: for who is able to judge this thy so great a people?" },
  { ref: "2 Chronicles 15:7", text: "Be ye strong therefore, and let not your hands be weak: for your work shall be rewarded." },
  { ref: "2 Chronicles 20:15", text: "And he said, Hearken ye, all Judah, and ye inhabitants of Jerusalem, and thou king Jehoshaphat, Thus saith the LORD unto you, Be not afraid nor dismayed by reason of this great multitude; for the battle is not yours, but God's." },
  { ref: "2 Chronicles 20:17", text: "Ye shall not need to fight in this battle: set yourselves, stand ye still, and see the salvation of the LORD with you, O Judah and Jerusalem: fear not, nor be dismayed; to morrow go out against them: for the LORD will be with you." },
  { ref: "2 Chronicles 31:21", text: "And in every work that he began in the service of the house of God, and in the law, and in the commandments, to seek his God, he did it with all his heart, and prospered." },
  { ref: "Nehemiah 8:10", text: "Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for this day is holy unto our Lord: neither be ye sorry; for the joy of the LORD is your strength." },
  { ref: "Nehemiah 2:18", text: "Then I told them of the hand of my God which was good upon me; as also the king's words that he had spoken unto me. And they said, Let us rise up and build. So they strengthened their hands for this good work." },
  { ref: "Nehemiah 6:9", text: "For they all made us afraid, saying, Their hands shall be weakened from the work, that it be not done. Now therefore, O God, strengthen my hands." },
  { ref: "Nehemiah 4:6", text: "So built we the wall; and all the wall was joined together unto the half thereof: for the people had a mind to work." },
  { ref: "Matthew 5:9", text: "Blessed are the peacemakers: for they shall be called the children of God." },
  { ref: "Matthew 6:34", text: "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day is the evil thereof." },
  { ref: "Matthew 7:7-8", text: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you: For every one that asketh receiveth; and he that seeketh findeth; and to him that knocketh it shall be opened." },
  { ref: "Matthew 11:28-30", text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest. Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls. For my yoke is easy, and my burden is light." },
  { ref: "Matthew 19:26", text: "But Jesus beheld them, and said unto them, With men this is impossible; but with God all things are possible." },
  { ref: "Matthew 22:37-39", text: "Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. This is the first and great commandment. And the second is like unto it, Thou shalt love thy neighbour as thyself." },
  { ref: "Matthew 5:5", text: "Blessed are the meek: for they shall inherit the earth." },
  { ref: "Matthew 6:33", text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you." },
  { ref: "Matthew 25:21", text: "His lord said unto him, Well done, thou good and faithful servant: thou hast been faithful over a few things, I will make thee ruler over many things: enter thou into the joy of thy lord." },
  { ref: "Mark 9:23", text: "Jesus said unto him, If thou canst believe, all things are possible to him that believeth." },
  { ref: "Mark 11:24", text: "Therefore I say unto you, What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them." },
  { ref: "Mark 4:39", text: "And he arose, and rebuked the wind, and said unto the sea, Peace, be still. And the wind ceased, and there was a great calm." },
  { ref: "Mark 6:31", text: "And he said unto them, Come ye yourselves apart into a desert place, and rest a while: for there were many coming and going, and they had no leisure so much as to eat." },
  { ref: "Mark 12:30-31", text: "And thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength: this is the first commandment. And the second is like, namely this, Thou shalt love thy neighbour as thyself. There is none other commandment greater than these." },
  { ref: "Luke 1:37", text: "For with God nothing shall be impossible." },
  { ref: "Luke 6:31", text: "And as ye would that men should do to you, do ye also to them likewise." },
  { ref: "Luke 6:38", text: "Give, and it shall be given unto you; good measure, pressed down, and shaken together, and running over, shall men give into your bosom. For with the same measure that ye mete withal it shall be measured to you again." },
  { ref: "Luke 12:32", text: "Fear not, little flock; for it is your Father's good pleasure to give you the kingdom." },
  { ref: "Luke 2:14", text: "Glory to God in the highest, and on earth peace, good will toward men." },
  { ref: "John 14:27", text: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid." },
  { ref: "John 16:33", text: "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world." },
  { ref: "John 15:12", text: "This is my commandment, That ye love one another, as I have loved you." },
  { ref: "John 8:12", text: "Then spake Jesus again unto them, saying, I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life." },
  { ref: "John 13:34", text: "A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another." },
  { ref: "John 1:5", text: "And the light shineth in darkness; and the darkness comprehended it not." },
  { ref: "John 14:1", text: "Let not your heart be troubled: ye believe in God, believe also in me." },
  { ref: "Romans 5:3-4", text: "And not only so, but we glory in tribulations also: knowing that tribulation worketh patience; And patience, experience; and experience, hope:" },
  { ref: "Romans 8:28", text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose." },
  { ref: "Romans 8:31", text: "What shall we then say to these things? If God be for us, who can be against us?" },
  { ref: "Romans 8:37", text: "Nay, in all these things we are more than conquerors through him that loved us." },
  { ref: "Romans 12:12", text: "Rejoicing in hope; patient in tribulation; continuing instant in prayer;" },
  { ref: "Romans 12:21", text: "Be not overcome of evil, but overcome evil with good." },
  { ref: "Romans 15:13", text: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost." },
  { ref: "Romans 12:10", text: "Be kindly affectioned one to another with brotherly love; in honour preferring one another;" },
  { ref: "Romans 15:4", text: "For whatsoever things were written aforetime were written for our learning, that we through patience and comfort of the scriptures might have hope." },
  { ref: "1 Corinthians 13:13", text: "And now abideth faith, hope, charity, these three; but the greatest of these is charity." },
  { ref: "1 Corinthians 13:7", text: "Beareth all things, believeth all things, hopeth all things, endureth all things." },
  { ref: "1 Corinthians 15:58", text: "Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labour is not in vain in the Lord." },
  { ref: "1 Corinthians 16:13-14", text: "Watch ye, stand fast in the faith, quit you like men, be strong. Let all your things be done with charity." },
  { ref: "1 Corinthians 15:57", text: "But thanks be to God, which giveth us the victory through our Lord Jesus Christ." },
  { ref: "1 Corinthians 9:24", text: "Know ye not that they which run in a race run all, but one receiveth the prize? So run, that ye may obtain." },
  { ref: "2 Corinthians 12:9", text: "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me." },
  { ref: "2 Corinthians 4:16", text: "For which cause we faint not; but though our outward man perish, yet the inward man is renewed day by day." },
  { ref: "2 Corinthians 9:7", text: "Every man according as he purposeth in his heart, so let him give; not grudgingly, or of necessity: for God loveth a cheerful giver." },
  { ref: "2 Corinthians 4:8-9", text: "We are troubled on every side, yet not distressed; we are perplexed, but not in despair; Persecuted, but not forsaken; cast down, but not destroyed;" },
  { ref: "2 Corinthians 13:11", text: "Finally, brethren, farewell. Be perfect, be of good comfort, be of one mind, live in peace; and the God of love and peace shall be with you." },
  { ref: "2 Corinthians 1:3-4", text: "Blessed be God, even the Father of our Lord Jesus Christ, the Father of mercies, and the God of all comfort; Who comforteth us in all our tribulation, that we may be able to comfort them which are in any trouble, by the comfort wherewith we ourselves are comforted of God." },
  { ref: "Galatians 6:9", text: "And let us not be weary in well doing: for in due season we shall reap, if we faint not." },
  { ref: "Galatians 5:22-23", text: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, Meekness, temperance: against such there is no law." },
  { ref: "Galatians 6:2", text: "Bear ye one another's burdens, and so fulfil the law of Christ." },
  { ref: "Galatians 6:10", text: "As we have therefore opportunity, let us do good unto all men, especially unto them who are of the household of faith." },
  { ref: "Galatians 5:13", text: "For, brethren, ye have been called unto liberty; only use not liberty for an occasion to the flesh, but by love serve one another." },
  { ref: "Ephesians 6:10", text: "Finally, my brethren, be strong in the Lord, and in the power of his might." },
  { ref: "Ephesians 4:2-3", text: "With all lowliness and meekness, with longsuffering, forbearing one another in love; Endeavouring to keep the unity of the Spirit in the bond of peace." },
  { ref: "Ephesians 4:32", text: "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you." },
  { ref: "Ephesians 2:8-9", text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast." },
  { ref: "Ephesians 3:16", text: "That he would grant you, according to the riches of his glory, to be strengthened with might by his Spirit in the inner man;" },
  { ref: "Ephesians 5:20", text: "Giving thanks always for all things unto God and the Father in the name of our Lord Jesus Christ;" },
  { ref: "Philippians 4:13", text: "I can do all things through Christ which strengtheneth me." },
  { ref: "Philippians 4:6-7", text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus." },
  { ref: "Philippians 4:8", text: "Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things." },
  { ref: "Philippians 4:4", text: "Rejoice in the Lord alway: and again I say, Rejoice." },
  { ref: "Philippians 3:13-14", text: "Brethren, I count not myself to have apprehended: but this one thing I do, forgetting those things which are behind, and reaching forth unto those things which are before, I press toward the mark for the prize of the high calling of God in Christ Jesus." },
  { ref: "Philippians 1:6", text: "Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ:" },
  { ref: "Philippians 2:3", text: "Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves." },
  { ref: "Philippians 4:19", text: "But my God shall supply all your need according to his riches in glory by Christ Jesus." },
  { ref: "Philippians 4:11", text: "Not that I speak in respect of want: for I have learned, in whatsoever state I am, therewith to be content." },
  { ref: "Colossians 3:23-24", text: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men; Knowing that of the Lord ye shall receive the reward of the inheritance: for ye serve the Lord Christ." },
  { ref: "Colossians 3:15", text: "And let the peace of God rule in your hearts, to the which also ye are called in one body; and be ye thankful." },
  { ref: "Colossians 3:17", text: "And whatsoever ye do in word or deed, do all in the name of the Lord Jesus, giving thanks to God and the Father by him." },
  { ref: "Colossians 1:11", text: "Strengthened with all might, according to his glorious power, unto all patience and longsuffering with joyfulness;" },
  { ref: "Colossians 4:2", text: "Continue in prayer, and watch in the same with thanksgiving;" },
  { ref: "1 Thessalonians 5:16-18", text: "Rejoice evermore. Pray without ceasing. In every thing give thanks: for this is the will of God in Christ Jesus concerning you." },
  { ref: "1 Thessalonians 5:11", text: "Wherefore comfort yourselves together, and edify one another, even as also ye do." },
  { ref: "1 Thessalonians 4:11", text: "And that ye study to be quiet, and to do your own business, and to work with your own hands, as we commanded you;" },
  { ref: "1 Thessalonians 3:12", text: "And the Lord make you to increase and abound in love one toward another, and toward all men, even as we do toward you:" },
  { ref: "1 Thessalonians 5:23", text: "And the very God of peace sanctify you wholly; and I pray God your whole spirit and soul and body be preserved blameless unto the coming of our Lord Jesus Christ." },
  { ref: "2 Thessalonians 3:13", text: "But ye, brethren, be not weary in well doing." },
  { ref: "2 Thessalonians 3:16", text: "Now the Lord of peace himself give you peace always by all means. The Lord be with you all." },
  { ref: "2 Thessalonians 2:16-17", text: "Now our Lord Jesus Christ himself, and God, even our Father, which hath loved us, and hath given us everlasting consolation and good hope through grace, Comfort your hearts, and stablish you in every good word and work." },
  { ref: "2 Thessalonians 3:5", text: "And the Lord direct your hearts into the love of God, and into the patient waiting for Christ." },
  { ref: "1 Timothy 6:6", text: "But godliness with contentment is great gain." },
  { ref: "1 Timothy 4:12", text: "Let no man despise thy youth; but be thou an example of the believers, in word, in conversation, in charity, in spirit, in faith, in purity." },
  { ref: "1 Timothy 6:8", text: "And having food and raiment let us be therewith content." },
  { ref: "1 Timothy 6:12", text: "Fight the good fight of faith, lay hold on eternal life, whereunto thou art also called, and hast professed a good profession before many witnesses." },
  { ref: "2 Timothy 1:7", text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind." },
  { ref: "2 Timothy 4:7", text: "I have fought a good fight, I have finished my course, I have kept the faith:" },
  { ref: "2 Timothy 2:1", text: "Thou therefore, my son, be strong in the grace that is in Christ Jesus." },
  { ref: "2 Timothy 2:15", text: "Study to shew thyself approved unto God, a workman that needeth not to be ashamed, rightly dividing the word of truth." },
  { ref: "Titus 3:2", text: "To speak evil of no man, to be no brawlers, but gentle, shewing all meekness unto all men." },
  { ref: "Hebrews 12:1", text: "Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us," },
  { ref: "Hebrews 11:1", text: "Now faith is the substance of things hoped for, the evidence of things not seen." },
  { ref: "Hebrews 4:16", text: "Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need." },
  { ref: "Hebrews 10:23", text: "Let us hold fast the profession of our faith without wavering; (for he is faithful that promised;)" },
  { ref: "Hebrews 10:35-36", text: "Cast not away therefore your confidence, which hath great recompence of reward. For ye have need of patience, that, after ye have done the will of God, ye might receive the promise." },
  { ref: "Hebrews 13:5-6", text: "Let your conversation be without covetousness; and be content with such things as ye have: for he hath said, I will never leave thee, nor forsake thee. So that we may boldly say, The Lord is my helper, and I will not fear what man shall do unto me." },
  { ref: "Hebrews 4:9-10", text: "There remaineth therefore a rest to the people of God. For he that is entered into his rest, he also hath ceased from his own works, as God did from his." },
  { ref: "Hebrews 13:8", text: "Jesus Christ the same yesterday, and to day, and for ever." },
  { ref: "James 1:2-4", text: "My brethren, count it all joy when ye fall into divers temptations; Knowing this, that the trying of your faith worketh patience. But let patience have her perfect work, that ye may be perfect and entire, wanting nothing." },
  { ref: "James 1:5", text: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him." },
  { ref: "James 1:12", text: "Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life, which the Lord hath promised to them that love him." },
  { ref: "James 1:19", text: "Wherefore, my beloved brethren, let every man be swift to hear, slow to speak, slow to wrath:" },
  { ref: "James 4:10", text: "Humble yourselves in the sight of the Lord, and he shall lift you up." },
  { ref: "James 5:7-8", text: "Be patient therefore, brethren, unto the coming of the Lord. Behold, the husbandman waiteth for the precious fruit of the earth, and hath long patience for it, until he receive the early and latter rain. Be ye also patient; stablish your hearts: for the coming of the Lord draweth nigh." },
  { ref: "James 3:17", text: "But the wisdom that is from above is first pure, then peaceable, gentle, and easy to be intreated, full of mercy and good fruits, without partiality, and without hypocrisy." },
  { ref: "1 Peter 5:7", text: "Casting all your care upon him; for he careth for you." },
  { ref: "1 Peter 5:10", text: "But the God of all grace, who hath called us unto his eternal glory by Christ Jesus, after that ye have suffered a while, make you perfect, stablish, strengthen, settle you." },
  { ref: "1 Peter 4:8", text: "And above all things have fervent charity among yourselves: for charity shall cover the multitude of sins." },
  { ref: "1 Peter 4:10", text: "As every man hath received the gift, even so minister the same one to another, as good stewards of the manifold grace of God." },
  { ref: "1 Peter 3:8", text: "Finally, be ye all of one mind, having compassion one of another, love as brethren, be pitiful, be courteous:" },
  { ref: "2 Peter 1:5-7", text: "And beside this, giving all diligence, add to your faith virtue; and to virtue knowledge; And to knowledge temperance; and to temperance patience; and to patience godliness; And to godliness brotherly kindness; and to brotherly kindness charity." },
  { ref: "2 Peter 3:18", text: "But grow in grace, and in the knowledge of our Lord and Saviour Jesus Christ. To him be glory both now and for ever. Amen." },
  { ref: "2 Peter 1:3", text: "According as his divine power hath given unto us all things that pertain unto life and godliness, through the knowledge of him that hath called us to glory and virtue:" },
  { ref: "1 John 4:7", text: "Beloved, let us love one another: for love is of God; and every one that loveth is born of God, and knoweth God." },
  { ref: "1 John 4:4", text: "Ye are of God, little children, and have overcome them: because greater is he that is in you, than he that is in the world." },
  { ref: "1 John 3:18", text: "My little children, let us not love in word, neither in tongue; but in deed and in truth." },
  { ref: "1 John 5:4", text: "For whatsoever is born of God overcometh the world: and this is the victory that overcometh the world, even our faith." },
  { ref: "1 John 4:19", text: "We love him, because he first loved us." },
  { ref: "Revelation 21:4", text: "And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away." },
  { ref: "Revelation 3:20", text: "Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him, and will sup with him, and he with me." },
];
