// Dietary Reference Intakes (DRIs) by age and sex, for the nutrition tracker's "% of target" display.
//
// PLAIN DATA ONLY. Every number here was checked against the National Academies (NASEM / IOM) summary
// tables and the NIH Office of Dietary Supplements fact sheets; see docs/DRI_SOURCES.md for the sources,
// dates checked and judgement calls. Do not edit a number without re-verifying it against a source.
//
// target = the RDA (Recommended Dietary Allowance) or the AI (Adequate Intake) for a healthy person of that
// age and sex. kind says which. ul = Tolerable Upper Intake Level, or null when none is established or it
// cannot be determined (the nutrient's ulScope says what the number covers).
//
// Excluded on purpose: infants (under 1), pregnancy and lactation (see PREGNANCY_LACTATION_NOTE).
// maxAge null means no upper bound.

export type Sex = 'male' | 'female';
export type DriKind = 'RDA' | 'AI';
export interface DriGroup { key: string; label: string; minAge: number; maxAge: number | null }
export interface DriEntry { target: number | null; kind: DriKind; ul: number | null }
export interface DriNutrient {
  key: string;
  unit: string;
  label: string;
  source: string;
  sourceUrl: string;
  ulScope: string;
  note: string;
  values: Record<string, { male: DriEntry; female: DriEntry }>;
}

export const DRI_GROUPS: DriGroup[] = [
  { key: '1-3', label: '1-3 years', minAge: 1, maxAge: 3 },
  { key: '4-8', label: '4-8 years', minAge: 4, maxAge: 8 },
  { key: '9-13', label: '9-13 years', minAge: 9, maxAge: 13 },
  { key: '14-18', label: '14-18 years', minAge: 14, maxAge: 18 },
  { key: '19-30', label: '19-30 years', minAge: 19, maxAge: 30 },
  { key: '31-50', label: '31-50 years', minAge: 31, maxAge: 50 },
  { key: '51-70', label: '51-70 years', minAge: 51, maxAge: 70 },
  { key: '71+', label: '71 years and older', minAge: 71, maxAge: null },
];

export const PREGNANCY_LACTATION_NOTE =
  'Nutrient needs are different during pregnancy and while breastfeeding (often higher), and these targets do not apply. Please ask your doctor or other clinician what is right for you.';

export const SAT_FAT_INFO = {
  key: 'sat_fat_g',
  unit: 'g',
  label: 'Saturated fat',
  dailyValue: 20,
  note:
    'The National Academies set no recommended intake or upper limit for saturated fat. Their advice is to keep it as low as possible while eating a nutritionally adequate diet. 20 g is the FDA Daily Value used on food labels, based on a 2,000 calorie diet; it is a label reference, not a personal target.',
};

export const DRI_NUTRIENTS: DriNutrient[] = [
  {
    key: 'fiber_g',
    unit: 'g',
    label: 'Fiber',
    source: 'IOM, Dietary Reference Intakes for Energy, Carbohydrate, Fiber, Fat, Fatty Acids, Cholesterol, Protein, and Amino Acids (2002/2005), as tabulated in NASEM 2019 Appendix J',
    sourceUrl: 'https://nap.nationalacademies.org/read/25353/chapter/28',
    ulScope: 'no UL established',
    note: 'Adequate Intake is 14 g of fiber per 1,000 kcal eaten, tabulated by age and sex. Most people eat well below it, so a higher intake is generally fine.',
    values: {
      '1-3': { male: { target: 19, kind: 'AI', ul: null }, female: { target: 19, kind: 'AI', ul: null } },
      '4-8': { male: { target: 25, kind: 'AI', ul: null }, female: { target: 25, kind: 'AI', ul: null } },
      '9-13': { male: { target: 31, kind: 'AI', ul: null }, female: { target: 26, kind: 'AI', ul: null } },
      '14-18': { male: { target: 38, kind: 'AI', ul: null }, female: { target: 26, kind: 'AI', ul: null } },
      '19-30': { male: { target: 38, kind: 'AI', ul: null }, female: { target: 25, kind: 'AI', ul: null } },
      '31-50': { male: { target: 38, kind: 'AI', ul: null }, female: { target: 25, kind: 'AI', ul: null } },
      '51-70': { male: { target: 30, kind: 'AI', ul: null }, female: { target: 21, kind: 'AI', ul: null } },
      '71+': { male: { target: 30, kind: 'AI', ul: null }, female: { target: 21, kind: 'AI', ul: null } },
    },
  },
  {
    key: 'sodium_mg',
    unit: 'mg',
    label: 'Sodium',
    source: 'NASEM, Dietary Reference Intakes for Sodium and Potassium (2019)',
    sourceUrl: 'https://nap.nationalacademies.org/read/25353/chapter/2',
    ulScope: 'chronic disease risk reduction level (CDRR), not a safe upper limit; no UL established',
    note: 'The target is the Adequate Intake, which is a minimum. The number in the upper-limit field is the 2019 Chronic Disease Risk Reduction Intake: reduce intake if above it.',
    values: {
      '1-3': { male: { target: 800, kind: 'AI', ul: 1200 }, female: { target: 800, kind: 'AI', ul: 1200 } },
      '4-8': { male: { target: 1000, kind: 'AI', ul: 1500 }, female: { target: 1000, kind: 'AI', ul: 1500 } },
      '9-13': { male: { target: 1200, kind: 'AI', ul: 1800 }, female: { target: 1200, kind: 'AI', ul: 1800 } },
      '14-18': { male: { target: 1500, kind: 'AI', ul: 2300 }, female: { target: 1500, kind: 'AI', ul: 2300 } },
      '19-30': { male: { target: 1500, kind: 'AI', ul: 2300 }, female: { target: 1500, kind: 'AI', ul: 2300 } },
      '31-50': { male: { target: 1500, kind: 'AI', ul: 2300 }, female: { target: 1500, kind: 'AI', ul: 2300 } },
      '51-70': { male: { target: 1500, kind: 'AI', ul: 2300 }, female: { target: 1500, kind: 'AI', ul: 2300 } },
      '71+': { male: { target: 1500, kind: 'AI', ul: 2300 }, female: { target: 1500, kind: 'AI', ul: 2300 } },
    },
  },
  {
    key: 'potassium_mg',
    unit: 'mg',
    label: 'Potassium',
    source: 'NASEM, Dietary Reference Intakes for Sodium and Potassium (2019)',
    sourceUrl: 'https://nap.nationalacademies.org/read/25353/chapter/2',
    ulScope: 'no UL established',
    note: 'Adequate Intake from the 2019 report. No upper limit was set for healthy people, but people with kidney disease or on certain medicines should ask their clinician before raising potassium.',
    values: {
      '1-3': { male: { target: 2000, kind: 'AI', ul: null }, female: { target: 2000, kind: 'AI', ul: null } },
      '4-8': { male: { target: 2300, kind: 'AI', ul: null }, female: { target: 2300, kind: 'AI', ul: null } },
      '9-13': { male: { target: 2500, kind: 'AI', ul: null }, female: { target: 2300, kind: 'AI', ul: null } },
      '14-18': { male: { target: 3000, kind: 'AI', ul: null }, female: { target: 2300, kind: 'AI', ul: null } },
      '19-30': { male: { target: 3400, kind: 'AI', ul: null }, female: { target: 2600, kind: 'AI', ul: null } },
      '31-50': { male: { target: 3400, kind: 'AI', ul: null }, female: { target: 2600, kind: 'AI', ul: null } },
      '51-70': { male: { target: 3400, kind: 'AI', ul: null }, female: { target: 2600, kind: 'AI', ul: null } },
      '71+': { male: { target: 3400, kind: 'AI', ul: null }, female: { target: 2600, kind: 'AI', ul: null } },
    },
  },
  {
    key: 'calcium_mg',
    unit: 'mg',
    label: 'Calcium',
    source: 'IOM, Dietary Reference Intakes for Calcium and Vitamin D (2011)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/Calcium-HealthProfessional/',
    ulScope: 'all sources (food and supplements)',
    note: 'Needs rise for women at 51 and for men at 71. Food first; the upper limit counts supplements plus food.',
    values: {
      '1-3': { male: { target: 700, kind: 'RDA', ul: 2500 }, female: { target: 700, kind: 'RDA', ul: 2500 } },
      '4-8': { male: { target: 1000, kind: 'RDA', ul: 2500 }, female: { target: 1000, kind: 'RDA', ul: 2500 } },
      '9-13': { male: { target: 1300, kind: 'RDA', ul: 3000 }, female: { target: 1300, kind: 'RDA', ul: 3000 } },
      '14-18': { male: { target: 1300, kind: 'RDA', ul: 3000 }, female: { target: 1300, kind: 'RDA', ul: 3000 } },
      '19-30': { male: { target: 1000, kind: 'RDA', ul: 2500 }, female: { target: 1000, kind: 'RDA', ul: 2500 } },
      '31-50': { male: { target: 1000, kind: 'RDA', ul: 2500 }, female: { target: 1000, kind: 'RDA', ul: 2500 } },
      '51-70': { male: { target: 1000, kind: 'RDA', ul: 2000 }, female: { target: 1200, kind: 'RDA', ul: 2000 } },
      '71+': { male: { target: 1200, kind: 'RDA', ul: 2000 }, female: { target: 1200, kind: 'RDA', ul: 2000 } },
    },
  },
  {
    key: 'iron_mg',
    unit: 'mg',
    label: 'Iron',
    source: 'IOM, Dietary Reference Intakes for Vitamin A, Vitamin K, Arsenic, Boron, Chromium, Copper, Iodine, Iron, Manganese, Molybdenum, Nickel, Silicon, Vanadium, and Zinc (2001)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/Iron-HealthProfessional/',
    ulScope: 'all sources (food and supplements)',
    note: 'Women need more iron from the teen years until 50. The report says vegetarians may need up to 1.8 times as much, because plant iron is absorbed less well.',
    values: {
      '1-3': { male: { target: 7, kind: 'RDA', ul: 40 }, female: { target: 7, kind: 'RDA', ul: 40 } },
      '4-8': { male: { target: 10, kind: 'RDA', ul: 40 }, female: { target: 10, kind: 'RDA', ul: 40 } },
      '9-13': { male: { target: 8, kind: 'RDA', ul: 40 }, female: { target: 8, kind: 'RDA', ul: 40 } },
      '14-18': { male: { target: 11, kind: 'RDA', ul: 45 }, female: { target: 15, kind: 'RDA', ul: 45 } },
      '19-30': { male: { target: 8, kind: 'RDA', ul: 45 }, female: { target: 18, kind: 'RDA', ul: 45 } },
      '31-50': { male: { target: 8, kind: 'RDA', ul: 45 }, female: { target: 18, kind: 'RDA', ul: 45 } },
      '51-70': { male: { target: 8, kind: 'RDA', ul: 45 }, female: { target: 8, kind: 'RDA', ul: 45 } },
      '71+': { male: { target: 8, kind: 'RDA', ul: 45 }, female: { target: 8, kind: 'RDA', ul: 45 } },
    },
  },
  {
    key: 'vitamin_d_mcg',
    unit: 'mcg',
    label: 'Vitamin D',
    source: 'IOM, Dietary Reference Intakes for Calcium and Vitamin D (2011)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/VitaminD-HealthProfessional/',
    ulScope: 'all sources (food and supplements; sunlight is not counted)',
    note: '15 mcg is 600 IU and 20 mcg is 800 IU. Sunlight also makes vitamin D, so food and supplements alone may understate real status.',
    values: {
      '1-3': { male: { target: 15, kind: 'RDA', ul: 63 }, female: { target: 15, kind: 'RDA', ul: 63 } },
      '4-8': { male: { target: 15, kind: 'RDA', ul: 75 }, female: { target: 15, kind: 'RDA', ul: 75 } },
      '9-13': { male: { target: 15, kind: 'RDA', ul: 100 }, female: { target: 15, kind: 'RDA', ul: 100 } },
      '14-18': { male: { target: 15, kind: 'RDA', ul: 100 }, female: { target: 15, kind: 'RDA', ul: 100 } },
      '19-30': { male: { target: 15, kind: 'RDA', ul: 100 }, female: { target: 15, kind: 'RDA', ul: 100 } },
      '31-50': { male: { target: 15, kind: 'RDA', ul: 100 }, female: { target: 15, kind: 'RDA', ul: 100 } },
      '51-70': { male: { target: 15, kind: 'RDA', ul: 100 }, female: { target: 15, kind: 'RDA', ul: 100 } },
      '71+': { male: { target: 20, kind: 'RDA', ul: 100 }, female: { target: 20, kind: 'RDA', ul: 100 } },
    },
  },
  {
    key: 'magnesium_mg',
    unit: 'mg',
    label: 'Magnesium',
    source: 'IOM, Dietary Reference Intakes for Calcium, Phosphorus, Magnesium, Vitamin D, and Fluoride (1997)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/Magnesium-HealthProfessional/',
    ulScope: 'supplements and pharmacological agents only (magnesium in food and water does not count toward the UL)',
    note: 'The upper limit applies only to magnesium from supplements and medicines, not to magnesium in food.',
    values: {
      '1-3': { male: { target: 80, kind: 'RDA', ul: 65 }, female: { target: 80, kind: 'RDA', ul: 65 } },
      '4-8': { male: { target: 130, kind: 'RDA', ul: 110 }, female: { target: 130, kind: 'RDA', ul: 110 } },
      '9-13': { male: { target: 240, kind: 'RDA', ul: 350 }, female: { target: 240, kind: 'RDA', ul: 350 } },
      '14-18': { male: { target: 410, kind: 'RDA', ul: 350 }, female: { target: 360, kind: 'RDA', ul: 350 } },
      '19-30': { male: { target: 400, kind: 'RDA', ul: 350 }, female: { target: 310, kind: 'RDA', ul: 350 } },
      '31-50': { male: { target: 420, kind: 'RDA', ul: 350 }, female: { target: 320, kind: 'RDA', ul: 350 } },
      '51-70': { male: { target: 420, kind: 'RDA', ul: 350 }, female: { target: 320, kind: 'RDA', ul: 350 } },
      '71+': { male: { target: 420, kind: 'RDA', ul: 350 }, female: { target: 320, kind: 'RDA', ul: 350 } },
    },
  },
  {
    key: 'zinc_mg',
    unit: 'mg',
    label: 'Zinc',
    source: 'IOM, Dietary Reference Intakes for Vitamin A, Vitamin K, Arsenic, Boron, Chromium, Copper, Iodine, Iron, Manganese, Molybdenum, Nickel, Silicon, Vanadium, and Zinc (2001)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/Zinc-HealthProfessional/',
    ulScope: 'all sources (food and supplements)',
    note: 'Too much zinc over time can lower copper, so supplements should stay under the upper limit.',
    values: {
      '1-3': { male: { target: 3, kind: 'RDA', ul: 7 }, female: { target: 3, kind: 'RDA', ul: 7 } },
      '4-8': { male: { target: 5, kind: 'RDA', ul: 12 }, female: { target: 5, kind: 'RDA', ul: 12 } },
      '9-13': { male: { target: 8, kind: 'RDA', ul: 23 }, female: { target: 8, kind: 'RDA', ul: 23 } },
      '14-18': { male: { target: 11, kind: 'RDA', ul: 34 }, female: { target: 9, kind: 'RDA', ul: 34 } },
      '19-30': { male: { target: 11, kind: 'RDA', ul: 40 }, female: { target: 8, kind: 'RDA', ul: 40 } },
      '31-50': { male: { target: 11, kind: 'RDA', ul: 40 }, female: { target: 8, kind: 'RDA', ul: 40 } },
      '51-70': { male: { target: 11, kind: 'RDA', ul: 40 }, female: { target: 8, kind: 'RDA', ul: 40 } },
      '71+': { male: { target: 11, kind: 'RDA', ul: 40 }, female: { target: 8, kind: 'RDA', ul: 40 } },
    },
  },
  {
    key: 'b12_mcg',
    unit: 'mcg',
    label: 'Vitamin B12',
    source: 'IOM, Dietary Reference Intakes for Thiamin, Riboflavin, Niacin, Vitamin B6, Folate, Vitamin B12, Pantothenic Acid, Biotin, and Choline (1998)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/VitaminB12-HealthProfessional/',
    ulScope: 'no UL established',
    note: 'Found mainly in animal foods. After 50 the report advises getting most of it from fortified foods or a supplement because absorption from food drops.',
    values: {
      '1-3': { male: { target: 0.9, kind: 'RDA', ul: null }, female: { target: 0.9, kind: 'RDA', ul: null } },
      '4-8': { male: { target: 1.2, kind: 'RDA', ul: null }, female: { target: 1.2, kind: 'RDA', ul: null } },
      '9-13': { male: { target: 1.8, kind: 'RDA', ul: null }, female: { target: 1.8, kind: 'RDA', ul: null } },
      '14-18': { male: { target: 2.4, kind: 'RDA', ul: null }, female: { target: 2.4, kind: 'RDA', ul: null } },
      '19-30': { male: { target: 2.4, kind: 'RDA', ul: null }, female: { target: 2.4, kind: 'RDA', ul: null } },
      '31-50': { male: { target: 2.4, kind: 'RDA', ul: null }, female: { target: 2.4, kind: 'RDA', ul: null } },
      '51-70': { male: { target: 2.4, kind: 'RDA', ul: null }, female: { target: 2.4, kind: 'RDA', ul: null } },
      '71+': { male: { target: 2.4, kind: 'RDA', ul: null }, female: { target: 2.4, kind: 'RDA', ul: null } },
    },
  },
  {
    key: 'vitamin_c_mg',
    unit: 'mg',
    label: 'Vitamin C',
    source: 'IOM, Dietary Reference Intakes for Vitamin C, Vitamin E, Selenium, and Carotenoids (2000)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/VitaminC-HealthProfessional/',
    ulScope: 'all sources (food and supplements)',
    note: 'People who smoke need about 35 mg more per day than the table shows.',
    values: {
      '1-3': { male: { target: 15, kind: 'RDA', ul: 400 }, female: { target: 15, kind: 'RDA', ul: 400 } },
      '4-8': { male: { target: 25, kind: 'RDA', ul: 650 }, female: { target: 25, kind: 'RDA', ul: 650 } },
      '9-13': { male: { target: 45, kind: 'RDA', ul: 1200 }, female: { target: 45, kind: 'RDA', ul: 1200 } },
      '14-18': { male: { target: 75, kind: 'RDA', ul: 1800 }, female: { target: 65, kind: 'RDA', ul: 1800 } },
      '19-30': { male: { target: 90, kind: 'RDA', ul: 2000 }, female: { target: 75, kind: 'RDA', ul: 2000 } },
      '31-50': { male: { target: 90, kind: 'RDA', ul: 2000 }, female: { target: 75, kind: 'RDA', ul: 2000 } },
      '51-70': { male: { target: 90, kind: 'RDA', ul: 2000 }, female: { target: 75, kind: 'RDA', ul: 2000 } },
      '71+': { male: { target: 90, kind: 'RDA', ul: 2000 }, female: { target: 75, kind: 'RDA', ul: 2000 } },
    },
  },
  {
    key: 'folate_mcg',
    unit: 'mcg DFE',
    label: 'Folate',
    source: 'IOM, Dietary Reference Intakes for Thiamin, Riboflavin, Niacin, Vitamin B6, Folate, Vitamin B12, Pantothenic Acid, Biotin, and Choline (1998)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/Folate-HealthProfessional/',
    ulScope: 'synthetic folic acid from supplements and fortified foods only (folate naturally in food does not count)',
    note: 'Measured in dietary folate equivalents (DFE). The upper limit is only for folic acid added to foods or taken as a supplement.',
    values: {
      '1-3': { male: { target: 150, kind: 'RDA', ul: 300 }, female: { target: 150, kind: 'RDA', ul: 300 } },
      '4-8': { male: { target: 200, kind: 'RDA', ul: 400 }, female: { target: 200, kind: 'RDA', ul: 400 } },
      '9-13': { male: { target: 300, kind: 'RDA', ul: 600 }, female: { target: 300, kind: 'RDA', ul: 600 } },
      '14-18': { male: { target: 400, kind: 'RDA', ul: 800 }, female: { target: 400, kind: 'RDA', ul: 800 } },
      '19-30': { male: { target: 400, kind: 'RDA', ul: 1000 }, female: { target: 400, kind: 'RDA', ul: 1000 } },
      '31-50': { male: { target: 400, kind: 'RDA', ul: 1000 }, female: { target: 400, kind: 'RDA', ul: 1000 } },
      '51-70': { male: { target: 400, kind: 'RDA', ul: 1000 }, female: { target: 400, kind: 'RDA', ul: 1000 } },
      '71+': { male: { target: 400, kind: 'RDA', ul: 1000 }, female: { target: 400, kind: 'RDA', ul: 1000 } },
    },
  },
  {
    key: 'vitamin_a_mcg',
    unit: 'mcg RAE',
    label: 'Vitamin A',
    source: 'IOM, Dietary Reference Intakes for Vitamin A, Vitamin K, Arsenic, Boron, Chromium, Copper, Iodine, Iron, Manganese, Molybdenum, Nickel, Silicon, Vanadium, and Zinc (2001)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/VitaminA-HealthProfessional/',
    ulScope: 'preformed vitamin A (retinol) from food and supplements only; carotenoids such as beta-carotene do not count',
    note: 'Measured in retinol activity equivalents (RAE). The upper limit applies to preformed vitamin A, not to carotenoids from plants.',
    values: {
      '1-3': { male: { target: 300, kind: 'RDA', ul: 600 }, female: { target: 300, kind: 'RDA', ul: 600 } },
      '4-8': { male: { target: 400, kind: 'RDA', ul: 900 }, female: { target: 400, kind: 'RDA', ul: 900 } },
      '9-13': { male: { target: 600, kind: 'RDA', ul: 1700 }, female: { target: 600, kind: 'RDA', ul: 1700 } },
      '14-18': { male: { target: 900, kind: 'RDA', ul: 2800 }, female: { target: 700, kind: 'RDA', ul: 2800 } },
      '19-30': { male: { target: 900, kind: 'RDA', ul: 3000 }, female: { target: 700, kind: 'RDA', ul: 3000 } },
      '31-50': { male: { target: 900, kind: 'RDA', ul: 3000 }, female: { target: 700, kind: 'RDA', ul: 3000 } },
      '51-70': { male: { target: 900, kind: 'RDA', ul: 3000 }, female: { target: 700, kind: 'RDA', ul: 3000 } },
      '71+': { male: { target: 900, kind: 'RDA', ul: 3000 }, female: { target: 700, kind: 'RDA', ul: 3000 } },
    },
  },
  {
    key: 'vitamin_e_mg',
    unit: 'mg alpha-tocopherol',
    label: 'Vitamin E',
    source: 'IOM, Dietary Reference Intakes for Vitamin C, Vitamin E, Selenium, and Carotenoids (2000)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/VitaminE-HealthProfessional/',
    ulScope: 'any form of supplemental alpha-tocopherol (supplements and fortified foods) only',
    note: 'Counts alpha-tocopherol only. The upper limit applies to vitamin E from supplements and fortified foods, not to the vitamin E in ordinary food.',
    values: {
      '1-3': { male: { target: 6, kind: 'RDA', ul: 200 }, female: { target: 6, kind: 'RDA', ul: 200 } },
      '4-8': { male: { target: 7, kind: 'RDA', ul: 300 }, female: { target: 7, kind: 'RDA', ul: 300 } },
      '9-13': { male: { target: 11, kind: 'RDA', ul: 600 }, female: { target: 11, kind: 'RDA', ul: 600 } },
      '14-18': { male: { target: 15, kind: 'RDA', ul: 800 }, female: { target: 15, kind: 'RDA', ul: 800 } },
      '19-30': { male: { target: 15, kind: 'RDA', ul: 1000 }, female: { target: 15, kind: 'RDA', ul: 1000 } },
      '31-50': { male: { target: 15, kind: 'RDA', ul: 1000 }, female: { target: 15, kind: 'RDA', ul: 1000 } },
      '51-70': { male: { target: 15, kind: 'RDA', ul: 1000 }, female: { target: 15, kind: 'RDA', ul: 1000 } },
      '71+': { male: { target: 15, kind: 'RDA', ul: 1000 }, female: { target: 15, kind: 'RDA', ul: 1000 } },
    },
  },
  {
    key: 'vitamin_k_mcg',
    unit: 'mcg',
    label: 'Vitamin K',
    source: 'IOM, Dietary Reference Intakes for Vitamin A, Vitamin K, Arsenic, Boron, Chromium, Copper, Iodine, Iron, Manganese, Molybdenum, Nickel, Silicon, Vanadium, and Zinc (2001)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/VitaminK-HealthProfessional/',
    ulScope: 'no UL established',
    note: 'Adequate Intake. People taking warfarin (Coumadin) should keep vitamin K steady and follow their clinician, not this target.',
    values: {
      '1-3': { male: { target: 30, kind: 'AI', ul: null }, female: { target: 30, kind: 'AI', ul: null } },
      '4-8': { male: { target: 55, kind: 'AI', ul: null }, female: { target: 55, kind: 'AI', ul: null } },
      '9-13': { male: { target: 60, kind: 'AI', ul: null }, female: { target: 60, kind: 'AI', ul: null } },
      '14-18': { male: { target: 75, kind: 'AI', ul: null }, female: { target: 75, kind: 'AI', ul: null } },
      '19-30': { male: { target: 120, kind: 'AI', ul: null }, female: { target: 90, kind: 'AI', ul: null } },
      '31-50': { male: { target: 120, kind: 'AI', ul: null }, female: { target: 90, kind: 'AI', ul: null } },
      '51-70': { male: { target: 120, kind: 'AI', ul: null }, female: { target: 90, kind: 'AI', ul: null } },
      '71+': { male: { target: 120, kind: 'AI', ul: null }, female: { target: 90, kind: 'AI', ul: null } },
    },
  },
  {
    key: 'thiamin_mg',
    unit: 'mg',
    label: 'Thiamin (B1)',
    source: 'IOM, Dietary Reference Intakes for Thiamin, Riboflavin, Niacin, Vitamin B6, Folate, Vitamin B12, Pantothenic Acid, Biotin, and Choline (1998)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/Thiamin-HealthProfessional/',
    ulScope: 'no UL established',
    note: 'Found in whole grains, pork, beans and fortified cereals.',
    values: {
      '1-3': { male: { target: 0.5, kind: 'RDA', ul: null }, female: { target: 0.5, kind: 'RDA', ul: null } },
      '4-8': { male: { target: 0.6, kind: 'RDA', ul: null }, female: { target: 0.6, kind: 'RDA', ul: null } },
      '9-13': { male: { target: 0.9, kind: 'RDA', ul: null }, female: { target: 0.9, kind: 'RDA', ul: null } },
      '14-18': { male: { target: 1.2, kind: 'RDA', ul: null }, female: { target: 1, kind: 'RDA', ul: null } },
      '19-30': { male: { target: 1.2, kind: 'RDA', ul: null }, female: { target: 1.1, kind: 'RDA', ul: null } },
      '31-50': { male: { target: 1.2, kind: 'RDA', ul: null }, female: { target: 1.1, kind: 'RDA', ul: null } },
      '51-70': { male: { target: 1.2, kind: 'RDA', ul: null }, female: { target: 1.1, kind: 'RDA', ul: null } },
      '71+': { male: { target: 1.2, kind: 'RDA', ul: null }, female: { target: 1.1, kind: 'RDA', ul: null } },
    },
  },
  {
    key: 'riboflavin_mg',
    unit: 'mg',
    label: 'Riboflavin (B2)',
    source: 'IOM, Dietary Reference Intakes for Thiamin, Riboflavin, Niacin, Vitamin B6, Folate, Vitamin B12, Pantothenic Acid, Biotin, and Choline (1998)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/Riboflavin-HealthProfessional/',
    ulScope: 'no UL established',
    note: 'Found in dairy, eggs, meat and fortified cereals.',
    values: {
      '1-3': { male: { target: 0.5, kind: 'RDA', ul: null }, female: { target: 0.5, kind: 'RDA', ul: null } },
      '4-8': { male: { target: 0.6, kind: 'RDA', ul: null }, female: { target: 0.6, kind: 'RDA', ul: null } },
      '9-13': { male: { target: 0.9, kind: 'RDA', ul: null }, female: { target: 0.9, kind: 'RDA', ul: null } },
      '14-18': { male: { target: 1.3, kind: 'RDA', ul: null }, female: { target: 1, kind: 'RDA', ul: null } },
      '19-30': { male: { target: 1.3, kind: 'RDA', ul: null }, female: { target: 1.1, kind: 'RDA', ul: null } },
      '31-50': { male: { target: 1.3, kind: 'RDA', ul: null }, female: { target: 1.1, kind: 'RDA', ul: null } },
      '51-70': { male: { target: 1.3, kind: 'RDA', ul: null }, female: { target: 1.1, kind: 'RDA', ul: null } },
      '71+': { male: { target: 1.3, kind: 'RDA', ul: null }, female: { target: 1.1, kind: 'RDA', ul: null } },
    },
  },
  {
    key: 'niacin_mg',
    unit: 'mg NE',
    label: 'Niacin (B3)',
    source: 'IOM, Dietary Reference Intakes for Thiamin, Riboflavin, Niacin, Vitamin B6, Folate, Vitamin B12, Pantothenic Acid, Biotin, and Choline (1998)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/Niacin-HealthProfessional/',
    ulScope: 'synthetic niacin from supplements and fortified foods only (niacin naturally in food does not count)',
    note: 'Measured in niacin equivalents (NE). The upper limit is for added niacin; high-dose niacin can cause flushing and liver problems.',
    values: {
      '1-3': { male: { target: 6, kind: 'RDA', ul: 10 }, female: { target: 6, kind: 'RDA', ul: 10 } },
      '4-8': { male: { target: 8, kind: 'RDA', ul: 15 }, female: { target: 8, kind: 'RDA', ul: 15 } },
      '9-13': { male: { target: 12, kind: 'RDA', ul: 20 }, female: { target: 12, kind: 'RDA', ul: 20 } },
      '14-18': { male: { target: 16, kind: 'RDA', ul: 30 }, female: { target: 14, kind: 'RDA', ul: 30 } },
      '19-30': { male: { target: 16, kind: 'RDA', ul: 35 }, female: { target: 14, kind: 'RDA', ul: 35 } },
      '31-50': { male: { target: 16, kind: 'RDA', ul: 35 }, female: { target: 14, kind: 'RDA', ul: 35 } },
      '51-70': { male: { target: 16, kind: 'RDA', ul: 35 }, female: { target: 14, kind: 'RDA', ul: 35 } },
      '71+': { male: { target: 16, kind: 'RDA', ul: 35 }, female: { target: 14, kind: 'RDA', ul: 35 } },
    },
  },
  {
    key: 'b6_mg',
    unit: 'mg',
    label: 'Vitamin B6',
    source: 'IOM, Dietary Reference Intakes for Thiamin, Riboflavin, Niacin, Vitamin B6, Folate, Vitamin B12, Pantothenic Acid, Biotin, and Choline (1998)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/VitaminB6-HealthProfessional/',
    ulScope: 'all sources (food and supplements); harm has only been reported from supplements',
    note: 'Needs rise after 50. Long-term high-dose supplements can damage nerves.',
    values: {
      '1-3': { male: { target: 0.5, kind: 'RDA', ul: 30 }, female: { target: 0.5, kind: 'RDA', ul: 30 } },
      '4-8': { male: { target: 0.6, kind: 'RDA', ul: 40 }, female: { target: 0.6, kind: 'RDA', ul: 40 } },
      '9-13': { male: { target: 1, kind: 'RDA', ul: 60 }, female: { target: 1, kind: 'RDA', ul: 60 } },
      '14-18': { male: { target: 1.3, kind: 'RDA', ul: 80 }, female: { target: 1.2, kind: 'RDA', ul: 80 } },
      '19-30': { male: { target: 1.3, kind: 'RDA', ul: 100 }, female: { target: 1.3, kind: 'RDA', ul: 100 } },
      '31-50': { male: { target: 1.3, kind: 'RDA', ul: 100 }, female: { target: 1.3, kind: 'RDA', ul: 100 } },
      '51-70': { male: { target: 1.7, kind: 'RDA', ul: 100 }, female: { target: 1.5, kind: 'RDA', ul: 100 } },
      '71+': { male: { target: 1.7, kind: 'RDA', ul: 100 }, female: { target: 1.5, kind: 'RDA', ul: 100 } },
    },
  },
  {
    key: 'choline_mg',
    unit: 'mg',
    label: 'Choline',
    source: 'IOM, Dietary Reference Intakes for Thiamin, Riboflavin, Niacin, Vitamin B6, Folate, Vitamin B12, Pantothenic Acid, Biotin, and Choline (1998)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/Choline-HealthProfessional/',
    ulScope: 'all sources (food and supplements)',
    note: 'Adequate Intake; eggs, meat, fish and soy are the main sources.',
    values: {
      '1-3': { male: { target: 200, kind: 'AI', ul: 1000 }, female: { target: 200, kind: 'AI', ul: 1000 } },
      '4-8': { male: { target: 250, kind: 'AI', ul: 1000 }, female: { target: 250, kind: 'AI', ul: 1000 } },
      '9-13': { male: { target: 375, kind: 'AI', ul: 2000 }, female: { target: 375, kind: 'AI', ul: 2000 } },
      '14-18': { male: { target: 550, kind: 'AI', ul: 3000 }, female: { target: 400, kind: 'AI', ul: 3000 } },
      '19-30': { male: { target: 550, kind: 'AI', ul: 3500 }, female: { target: 425, kind: 'AI', ul: 3500 } },
      '31-50': { male: { target: 550, kind: 'AI', ul: 3500 }, female: { target: 425, kind: 'AI', ul: 3500 } },
      '51-70': { male: { target: 550, kind: 'AI', ul: 3500 }, female: { target: 425, kind: 'AI', ul: 3500 } },
      '71+': { male: { target: 550, kind: 'AI', ul: 3500 }, female: { target: 425, kind: 'AI', ul: 3500 } },
    },
  },
  {
    key: 'phosphorus_mg',
    unit: 'mg',
    label: 'Phosphorus',
    source: 'IOM, Dietary Reference Intakes for Calcium, Phosphorus, Magnesium, Vitamin D, and Fluoride (1997)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/Phosphorus-HealthProfessional/',
    ulScope: 'all sources (food and supplements)',
    note: 'Teens need more than adults. Deficiency is rare because phosphorus is in most foods.',
    values: {
      '1-3': { male: { target: 460, kind: 'RDA', ul: 3000 }, female: { target: 460, kind: 'RDA', ul: 3000 } },
      '4-8': { male: { target: 500, kind: 'RDA', ul: 3000 }, female: { target: 500, kind: 'RDA', ul: 3000 } },
      '9-13': { male: { target: 1250, kind: 'RDA', ul: 4000 }, female: { target: 1250, kind: 'RDA', ul: 4000 } },
      '14-18': { male: { target: 1250, kind: 'RDA', ul: 4000 }, female: { target: 1250, kind: 'RDA', ul: 4000 } },
      '19-30': { male: { target: 700, kind: 'RDA', ul: 4000 }, female: { target: 700, kind: 'RDA', ul: 4000 } },
      '31-50': { male: { target: 700, kind: 'RDA', ul: 4000 }, female: { target: 700, kind: 'RDA', ul: 4000 } },
      '51-70': { male: { target: 700, kind: 'RDA', ul: 4000 }, female: { target: 700, kind: 'RDA', ul: 4000 } },
      '71+': { male: { target: 700, kind: 'RDA', ul: 3000 }, female: { target: 700, kind: 'RDA', ul: 3000 } },
    },
  },
  {
    key: 'copper_mcg',
    unit: 'mcg',
    label: 'Copper',
    source: 'IOM, Dietary Reference Intakes for Vitamin A, Vitamin K, Arsenic, Boron, Chromium, Copper, Iodine, Iron, Manganese, Molybdenum, Nickel, Silicon, Vanadium, and Zinc (2001)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/Copper-HealthProfessional/',
    ulScope: 'all sources (food and supplements)',
    note: 'Found in shellfish, nuts, seeds, whole grains and organ meats.',
    values: {
      '1-3': { male: { target: 340, kind: 'RDA', ul: 1000 }, female: { target: 340, kind: 'RDA', ul: 1000 } },
      '4-8': { male: { target: 440, kind: 'RDA', ul: 3000 }, female: { target: 440, kind: 'RDA', ul: 3000 } },
      '9-13': { male: { target: 700, kind: 'RDA', ul: 5000 }, female: { target: 700, kind: 'RDA', ul: 5000 } },
      '14-18': { male: { target: 890, kind: 'RDA', ul: 8000 }, female: { target: 890, kind: 'RDA', ul: 8000 } },
      '19-30': { male: { target: 900, kind: 'RDA', ul: 10000 }, female: { target: 900, kind: 'RDA', ul: 10000 } },
      '31-50': { male: { target: 900, kind: 'RDA', ul: 10000 }, female: { target: 900, kind: 'RDA', ul: 10000 } },
      '51-70': { male: { target: 900, kind: 'RDA', ul: 10000 }, female: { target: 900, kind: 'RDA', ul: 10000 } },
      '71+': { male: { target: 900, kind: 'RDA', ul: 10000 }, female: { target: 900, kind: 'RDA', ul: 10000 } },
    },
  },
  {
    key: 'manganese_mg',
    unit: 'mg',
    label: 'Manganese',
    source: 'IOM, Dietary Reference Intakes for Vitamin A, Vitamin K, Arsenic, Boron, Chromium, Copper, Iodine, Iron, Manganese, Molybdenum, Nickel, Silicon, Vanadium, and Zinc (2001)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/Manganese-HealthProfessional/',
    ulScope: 'all sources (food, water and supplements)',
    note: 'Adequate Intake. Found in whole grains, nuts, leafy vegetables and tea.',
    values: {
      '1-3': { male: { target: 1.2, kind: 'AI', ul: 2 }, female: { target: 1.2, kind: 'AI', ul: 2 } },
      '4-8': { male: { target: 1.5, kind: 'AI', ul: 3 }, female: { target: 1.5, kind: 'AI', ul: 3 } },
      '9-13': { male: { target: 1.9, kind: 'AI', ul: 6 }, female: { target: 1.6, kind: 'AI', ul: 6 } },
      '14-18': { male: { target: 2.2, kind: 'AI', ul: 9 }, female: { target: 1.6, kind: 'AI', ul: 9 } },
      '19-30': { male: { target: 2.3, kind: 'AI', ul: 11 }, female: { target: 1.8, kind: 'AI', ul: 11 } },
      '31-50': { male: { target: 2.3, kind: 'AI', ul: 11 }, female: { target: 1.8, kind: 'AI', ul: 11 } },
      '51-70': { male: { target: 2.3, kind: 'AI', ul: 11 }, female: { target: 1.8, kind: 'AI', ul: 11 } },
      '71+': { male: { target: 2.3, kind: 'AI', ul: 11 }, female: { target: 1.8, kind: 'AI', ul: 11 } },
    },
  },
  {
    key: 'selenium_mcg',
    unit: 'mcg',
    label: 'Selenium',
    source: 'IOM, Dietary Reference Intakes for Vitamin C, Vitamin E, Selenium, and Carotenoids (2000)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/Selenium-HealthProfessional/',
    ulScope: 'all sources (food and supplements)',
    note: 'Brazil nuts are very high in selenium, so keep to a few a day.',
    values: {
      '1-3': { male: { target: 20, kind: 'RDA', ul: 90 }, female: { target: 20, kind: 'RDA', ul: 90 } },
      '4-8': { male: { target: 30, kind: 'RDA', ul: 150 }, female: { target: 30, kind: 'RDA', ul: 150 } },
      '9-13': { male: { target: 40, kind: 'RDA', ul: 280 }, female: { target: 40, kind: 'RDA', ul: 280 } },
      '14-18': { male: { target: 55, kind: 'RDA', ul: 400 }, female: { target: 55, kind: 'RDA', ul: 400 } },
      '19-30': { male: { target: 55, kind: 'RDA', ul: 400 }, female: { target: 55, kind: 'RDA', ul: 400 } },
      '31-50': { male: { target: 55, kind: 'RDA', ul: 400 }, female: { target: 55, kind: 'RDA', ul: 400 } },
      '51-70': { male: { target: 55, kind: 'RDA', ul: 400 }, female: { target: 55, kind: 'RDA', ul: 400 } },
      '71+': { male: { target: 55, kind: 'RDA', ul: 400 }, female: { target: 55, kind: 'RDA', ul: 400 } },
    },
  },
  {
    key: 'iodine_mcg',
    unit: 'mcg',
    label: 'Iodine',
    source: 'IOM, Dietary Reference Intakes for Vitamin A, Vitamin K, Arsenic, Boron, Chromium, Copper, Iodine, Iron, Manganese, Molybdenum, Nickel, Silicon, Vanadium, and Zinc (2001)',
    sourceUrl: 'https://ods.od.nih.gov/factsheets/Iodine-HealthProfessional/',
    ulScope: 'all sources (food and supplements)',
    note: 'Iodized salt, dairy, eggs and seafood are the main sources. Sea salt and most specialty salts are often not iodized.',
    values: {
      '1-3': { male: { target: 90, kind: 'RDA', ul: 200 }, female: { target: 90, kind: 'RDA', ul: 200 } },
      '4-8': { male: { target: 90, kind: 'RDA', ul: 300 }, female: { target: 90, kind: 'RDA', ul: 300 } },
      '9-13': { male: { target: 120, kind: 'RDA', ul: 600 }, female: { target: 120, kind: 'RDA', ul: 600 } },
      '14-18': { male: { target: 150, kind: 'RDA', ul: 900 }, female: { target: 150, kind: 'RDA', ul: 900 } },
      '19-30': { male: { target: 150, kind: 'RDA', ul: 1100 }, female: { target: 150, kind: 'RDA', ul: 1100 } },
      '31-50': { male: { target: 150, kind: 'RDA', ul: 1100 }, female: { target: 150, kind: 'RDA', ul: 1100 } },
      '51-70': { male: { target: 150, kind: 'RDA', ul: 1100 }, female: { target: 150, kind: 'RDA', ul: 1100 } },
      '71+': { male: { target: 150, kind: 'RDA', ul: 1100 }, female: { target: 150, kind: 'RDA', ul: 1100 } },
    },
  },
];
