// Writes supabase/MIGRATION_MAP.md: which repo migration file each applied (live) migration came from, which repo files have
// no live match yet (not applied), and which live migrations have no repo file. The repo names files NNNN_name.sql; the live
// database records a timestamp version plus the name, so the two are matched by name.
//
//   node scripts/migration-map.mjs
//
// The live list comes from supabase/live-migrations.txt, a snapshot copied from Supabase's migration list. Refresh that file
// first when you want an up to date map.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "supabase", "migrations");

const repo = readdirSync(dir)
  .filter((f) => /^\d{4}_.+\.sql$/.test(f))
  .sort()
  .map((file) => ({ file, number: file.slice(0, 4), name: file.slice(5, -4) }));

const live = readFileSync(join(root, "supabase", "live-migrations.txt"), "utf8")
  .split(/\r?\n/)
  .filter((l) => l && !l.startsWith("#"))
  .map((l) => {
    const [version, ...rest] = l.trim().split(/\s+/);
    return { version, name: rest.join(" ") };
  });

// A live name may carry the repo number as a prefix ("0116_client_intake"); strip it so both sides compare on the bare name.
const bare = (n) => n.replace(/^\d{4}_/, "");

const repoByName = new Map();
for (const r of repo) {
  const list = repoByName.get(r.name) ?? [];
  list.push(r);
  repoByName.set(r.name, list);
}

const matchedRepo = new Set();
const rows = live.map((l) => {
  const hit = (repoByName.get(bare(l.name)) ?? []).find((r) => !matchedRepo.has(r.file));
  if (hit) matchedRepo.add(hit.file);
  return { ...l, file: hit?.file ?? null };
});

const unapplied = repo.filter((r) => !matchedRepo.has(r.file));
const liveOnly = rows.filter((r) => !r.file);

const out = [];
out.push("# Migration map");
out.push("");
out.push("Generated by `node scripts/migration-map.mjs` from `supabase/live-migrations.txt` (a snapshot of the live database's migration list) and the files in `supabase/migrations/`. Matching is by name: the repo uses `NNNN_name.sql`; the live database records a timestamp version and the name.");
out.push("");
out.push(`- Live migrations: ${live.length}`);
out.push(`- Repo files: ${repo.length}`);
out.push(`- Repo files with no live match (not applied yet, or applied under another name): ${unapplied.length}`);
out.push(`- Live migrations with no repo file: ${liveOnly.length}`);
out.push("");
out.push("## Notes on the mismatches (checked by reading the files, not by diffing the database)");
out.push("");
out.push("- `0001` and `0002` are the original schema, applied before migration tracking began, so they have no live entry.");
out.push("- `0105_group_kind` appears live as two entries, `group_one_on_one_flag` and `group_kind_enum`.");
out.push("- `0166_public_share_org_background_access` most likely appears live as `grant_anon_groups_organization_id` and `organizations_select_public_workout_share`. Confirm before relying on it.");
out.push("- `0207_reschedule_booking_overlap_guard` is replaced by the later `reschedule_booking` definitions in `0208` onward, which are live.");
out.push("- The live-only entries named fix_/hotfix_ are corrections applied straight to the database. Their SQL is not saved as files here; a database rebuilt only from the repo would miss them.");
out.push("- `0236` and everything from `0237` up that is listed below are genuinely pending, apart from the ones already applied under a different name.");
out.push("");
out.push("## Repo files not applied to the live database");
out.push("");
if (unapplied.length === 0) out.push("None.");
else {
  out.push("Apply these in the order set out in the project's migration notes, not simply by number: some depend on code being live first.");
  out.push("");
  for (const r of unapplied) out.push(`- \`${r.file}\``);
}
out.push("");
out.push("## Live migrations with no repo file");
out.push("");
if (liveOnly.length === 0) out.push("None.");
else {
  out.push("These were applied directly (for example from the Supabase tool) and never saved as a file, or were saved under a different name. Check each before relying on the repo to rebuild the database.");
  out.push("");
  for (const r of liveOnly) out.push(`- \`${r.version}\` ${r.name}`);
}
out.push("");
out.push("## Applied: live version to repo file");
out.push("");
out.push("| Live version | Name | Repo file |");
out.push("| --- | --- | --- |");
for (const r of rows) out.push(`| ${r.version} | ${r.name} | ${r.file ? `\`${r.file}\`` : "(none)"} |`);
out.push("");

writeFileSync(join(root, "supabase", "MIGRATION_MAP.md"), out.join("\n"));
console.log(`live ${live.length}, repo ${repo.length}, unapplied ${unapplied.length}, live-only ${liveOnly.length}`);
