// The probe for step 23 (0281): proves, on the live database and without leaving anything behind, that
//  * a booking the SERVER makes by itself (the nightly top-up of a weekly schedule) does NOT bring a set-aside client back,
//  * a message from the client DOES, and a message the coach sends does NOT,
//  * an ordinary booking (not made by the server) DOES.
// There is no separate test project, so it runs inside one transaction: it applies 0281's own SQL, picks one existing client and coach pair, tries the four
// cases, and ends with an intentional error that carries the result, so the whole transaction is rolled back and nothing is kept (not even 0281 itself).
export const probeSql = (migration0281) =>
  [
    "-- STEP 23 PROBE (run BEFORE step 23, changes NOTHING). Paste the whole file and run it once.",
    "-- It applies 0281 inside a transaction, tries four cases on one existing client, then ends with an intentional red error that holds the result and",
    "-- rolls everything back (the table, the triggers and the test rows are all undone).",
    '-- WHAT YOU SHOULD SEE: a red error whose text starts "PROBE RESULT" and says  server booking left them set aside: true | client message brought them back: true | coach message left them set aside: true | ordinary booking brought them back: true',
    "-- That error is the expected answer, not a failure. If any value is false, or the error says anything else, copy it and send it to Spot. Then run   rollback;   once.",
    "-- Safe to run twice. It never writes anything that survives.",
    "begin;",
    "",
    migration0281,
    "",
    "do $probe$",
    "declare",
    "  v_athlete uuid;",
    "  v_group uuid;",
    "  v_coach uuid;",
    "  a boolean;",
    "  b boolean;",
    "  c boolean;",
    "  d boolean;",
    "  v_err text := '';",
    "begin",
    "  select gm.profile_id, gm.group_id, cg.profile_id into v_athlete, v_group, v_coach",
    "  from public.group_memberships gm",
    "  join public.group_memberships cg on cg.group_id = gm.group_id and cg.role = 'coach' and cg.profile_id <> gm.profile_id",
    "  where gm.role = 'athlete'",
    "  order by gm.joined_at nulls last",
    "  limit 1;",
    "  if v_athlete is null then",
    "    raise exception 'PROBE RESULT: no client and coach pair to test with, nothing was proven';",
    "  end if;",
    "",
    "  -- A: a booking made by the server (service role) leaves a set-aside client set aside.",
    "  insert into public.client_inactive (athlete_id, group_id, note) values (v_athlete, v_group, 'probe');",
    "  begin",
    "    execute 'set local role service_role';",
    "    perform set_config('request.jwt.claim.role', 'service_role', true);",
    "    perform set_config('request.jwt.claim.sub', '', true);",
    "    insert into public.bookings (coach_id, athlete_id, group_id, start_at, end_at, status, credit_state)",
    "    values (v_coach, v_athlete, v_group, now() + interval '400 days 3 minutes', now() + interval '400 days 63 minutes', 'confirmed', 'unsettled');",
    "    execute 'reset role';",
    "  exception when others then",
    "    execute 'reset role';",
    "    v_err := v_err || ' [server booking error: ' || sqlerrm || ']';",
    "  end;",
    "  perform set_config('request.jwt.claim.role', '', true);",
    "  a := exists (select 1 from public.client_inactive where athlete_id = v_athlete and group_id = v_group);",
    "",
    "  -- C: a message the coach sends leaves them set aside (still set from A).",
    "  insert into public.direct_messages (group_id, sender_id, recipient_id, body) values (v_group, v_coach, v_athlete, 'probe');",
    "  c := exists (select 1 from public.client_inactive where athlete_id = v_athlete and group_id = v_group);",
    "",
    "  -- B: a message from the client brings them back.",
    "  insert into public.direct_messages (group_id, sender_id, recipient_id, body) values (v_group, v_athlete, v_coach, 'probe');",
    "  b := not exists (select 1 from public.client_inactive where athlete_id = v_athlete and group_id = v_group);",
    "",
    "  -- D: an ordinary booking (not made by the server) brings them back.",
    "  insert into public.client_inactive (athlete_id, group_id, note) values (v_athlete, v_group, 'probe');",
    "  begin",
    "    insert into public.bookings (coach_id, athlete_id, group_id, start_at, end_at, status, credit_state)",
    "    values (v_coach, v_athlete, v_group, now() + interval '401 days 3 minutes', now() + interval '401 days 63 minutes', 'confirmed', 'unsettled');",
    "  exception when others then",
    "    v_err := v_err || ' [ordinary booking error: ' || sqlerrm || ']';",
    "  end;",
    "  d := not exists (select 1 from public.client_inactive where athlete_id = v_athlete and group_id = v_group);",
    "",
    "  raise exception 'PROBE RESULT (rolled back, nothing kept) | server booking left them set aside: % | client message brought them back: % | coach message left them set aside: % | ordinary booking brought them back: % %', a::text, b::text, c::text, d::text, v_err;",
    "end",
    "$probe$;",
    "",
    "rollback;",
    "",
  ].join("\n");
