-- Meal plans generated by the coach's own deterministic recipe engine
-- (ported from their standalone HTML tool) — one row per client per day.
-- No AI involved yet; this just persists what the engine + coach's
-- recipe selections produced, so it's real data ready to eventually
-- surface on the client's calendar.
create table public.meal_plans (
  id uuid primary key default uuid_generate_v4(),
  athlete_id uuid not null references public.profiles(id) on delete cascade,
  group_id uuid not null references public.groups(id) on delete cascade,
  log_date date not null,
  archetype text not null,
  meal_count int not null,
  include_snack boolean not null default false,
  carb_cycling boolean not null default false,
  rationale text,
  macros jsonb not null,
  meals jsonb not null,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  unique (athlete_id, log_date)
);

alter table public.meal_plans enable row level security;

create policy "meal_plans_coach_manage" on public.meal_plans for all
  to authenticated
  using (public.is_group_coach(group_id))
  with check (public.is_group_coach(group_id));

create policy "meal_plans_athlete_select_own" on public.meal_plans for select
  to authenticated
  using (athlete_id = auth.uid());
